import type { Recipe } from "../lib/types";
export const recipes: Recipe[] = [
	{
		name: "Macaroni Salad",
		group: "Salads",
		ingredients: [
			{ value: "Pasta", slot: "Ingredient 1" },
			{ value: "Cucumber", slot: "Ingredient 2" },
			{ value: "Mayonnaise (any)", slot: "Ingredient 3" },
			{ value: "Carrot", slot: "Ingredient 4" },
		],
		baseValue: { value: 1859, unit: "G" },
		effect: "Stamina Saver Lv. 4",
		whereToUnlock: "Nadine's Bistro",
	},
	{
		name: "Guacamole Salad",
		group: "Salads",
		ingredients: [
			{ value: "Avocado", slot: "Ingredient 1" },
			{ value: "Onion", slot: "Ingredient 2" },
			{ value: "Tomato", slot: "Ingredient 3" },
			{ value: "Salt", slot: "Ingredient 4" },
		],
		baseValue: { value: 1309, unit: "G" },
		effect: "Stamina Saver Lv. 3",
		whereToUnlock: "Plower title, Nadine's Bistro",
	},
	{
		name: "Kinpira Gobo",
		group: "Salads",
		ingredients: [
			{ value: "Burdock", slot: "Ingredient 1" },
			{ value: "Carrot", slot: "Ingredient 2" },
			{ value: "Chili Pepper", slot: "Ingredient 3" },
		],
		baseValue: { value: 909, unit: "G" },
		effect: "Stamina Saver Lv. 3",
		whereToUnlock: "Clara's Diner",
	},
	{
		name: "Marinated Peppers",
		group: "Salads",
		ingredients: [
			{ value: "Red Bell Pepper", slot: "Ingredient 1" },
			{ value: "Vinegar", slot: "Ingredient 2" },
			{
				value: ["Oil", "Nut Oil", "Herb Oil", "Olive Oil", "Grape Oil"],
				slot: "Ingredient 3",
			},
		],
		baseValue: { value: 598, unit: "G" },
		effect: "Stamina Saver Lv. 2",
		whereToUnlock: "Mini Madeleine's",
	},
	{
		name: "Mixed Salad",
		group: "Salads",
		ingredients: [
			{ value: "Tomato", slot: "Ingredient 1" },
			{ value: "Cucumber", slot: "Ingredient 2" },
			{
				value: [
					"Cucumber",
					"Onion",
					"Asparagus",
					"Tomato",
					"Red Bell Pepper",
					"Carrot",
					"Turnip",
					"Sweet Potato",
					"Pumpkin",
					"Eggplant",
				],
				slot: "Ingredient 3",
			},
		],
		baseValue: { value: 404, unit: "G" },
		effect: "Stamina Saver Lv. 1",
		whereToUnlock: "Clara's Diner",
	},
	{
		name: "Turnip Salad",
		group: "Salads",
		ingredients: [{ value: "Turnip", slot: "Ingredient 1" }],
		baseValue: { value: 260, unit: "G" },
		effect: "Stamina Saver Lv. 1",
		whereToUnlock: "Available at the start",
	},
	{
		name: "Herb Salad",
		group: "Salads",
		ingredients: [
			{ value: ["Mint", "Chamomile", "Lavender"], slot: "Ingredient 1" },
			{ value: ["Mint", "Chamomile", "Lavender"], slot: "Ingredient 2" },
		],
		baseValue: { value: 137, unit: "G" },
		effect: "Stamina Saver Lv. 1",
		whereToUnlock: "Available at the start",
	},
	{
		name: "Tomato Salad",
		group: "Salads",
		ingredients: [
			{ value: "Tomato", slot: "Ingredient 1" },
			{ value: ["Mint", "Chamomile", "Lavender"], slot: "Ingredient 2" },
		],
		baseValue: { value: 126, unit: "G" },
		effect: "Stamina Saver Lv. 1",
		whereToUnlock: "Mini Madeleine's",
	},
	{
		name: "Caprese Salad",
		group: "Salads",
		ingredients: [
			{ value: "Tomato", slot: "Ingredient 1" },
			{ value: "Cheese (any)", slot: "Ingredient 2" },
			{ value: "Olive Oil", slot: "Ingredient 3" },
			{ value: "Salt", slot: "Ingredient 4" },
		],
		baseValue: { value: 2429, unit: "G" },
		effect: "Watering Rare Crop % Lv. 4",
		whereToUnlock: "Avant-Garde Crops request from Erik",
	},
	{
		name: "Poke",
		group: "Salads",
		ingredients: [
			{ value: "Avocado", slot: "Ingredient 1" },
			{ value: "Salmon", slot: "Ingredient 2" },
			{ value: "Soy Sauce", slot: "Ingredient 3" },
		],
		baseValue: { value: 1197, unit: "G" },
		effect: "Watering Rare Crop % Lv. 3",
		whereToUnlock: "Mini Madeleine's",
	},
	{
		name: "Mashed Potatoes",
		group: "Salads",
		ingredients: [
			{ value: "Potato", slot: "Ingredient 1" },
			{ value: "Butter (any)", slot: "Ingredient 2" },
		],
		baseValue: { value: 677, unit: "G" },
		effect: "Watering Rare Crop % Lv. 2",
		whereToUnlock: "Café Madeleine",
	},
	{
		name: "Onion Salad",
		group: "Salads",
		ingredients: [{ value: "Onion", slot: "Ingredient 1" }],
		baseValue: { value: 325, unit: "G" },
		effect: "Watering Rare Crop % Lv. 1",
		whereToUnlock: "Café Madeleine",
	},
	{
		name: "Asparagus Soup",
		group: "Soups",
		ingredients: [
			{ value: "Asparagus", slot: "Ingredient 1" },
			{ value: ["Milk", "Buffalo Milk"], slot: "Ingredient 2" },
			{
				value: ["Oil", "Nut Oil", "Herb Oil", "Olive Oil", "Grape Oil"],
				slot: "Ingredient 3",
			},
			{ value: "Onion", slot: "Ingredient 4" },
		],
		baseValue: { value: 1728, unit: "G" },
		effect: "Rod Durability Up Lv. 4",
		usedForFestival: "Hearth Day",
		whereToUnlock: "Clara's Diner",
	},
	{
		name: "Onion Soup",
		group: "Soups",
		ingredients: [
			{ value: "Onion", slot: "Ingredient 1" },
			{ value: "Butter (any)", slot: "Ingredient 2" },
		],
		baseValue: { value: 1024, unit: "G" },
		effect: "Rod Durability Up Lv. 3",
		usedForFestival: "Hearth Day",
		whereToUnlock: "Mini Madeleine's",
	},
	{
		name: "Radish Soup",
		group: "Soups",
		ingredients: [
			{ value: "Radish", slot: "Ingredient 1" },
			{ value: ["Milk", "Buffalo Milk"], slot: "Ingredient 2" },
			{ value: "Salt", slot: "Ingredient 3" },
		],
		baseValue: { value: 770, unit: "G" },
		effect: "Rod Durability Up Lv. 2",
		usedForFestival: "Hearth Day",
		whereToUnlock: "Pantry Patron request from Mina",
	},
	{
		name: "Miso Soup",
		group: "Soups",
		ingredients: [
			{ value: "Miso", slot: "Ingredient 1" },
			{
				value: [
					"Tofu",
					"Green Onion",
					"Fried Tofu",
					"Potato",
					"Shimeji Mushroom",
				],
				slot: "Ingredient 2",
			},
		],
		baseValue: { value: 260, unit: "G" },
		effect: "Rod Durability Up Lv. 1",
		usedForFestival: "Hearth Day",
		whereToUnlock: "Clara's Diner",
	},
	{
		name: "Corn Soup",
		group: "Soups",
		ingredients: [
			{ value: "Corn", slot: "Ingredient 1" },
			{ value: ["Milk", "Buffalo Milk"], slot: "Ingredient 2" },
			{ value: "Butter (any)", slot: "Ingredient 3" },
			{ value: "Onion", slot: "Ingredient 4" },
		],
		baseValue: { value: 1815, unit: "G" },
		effect: "Run Speed Up Lv. 4",
		usedForFestival: "Hearth Day",
		whereToUnlock: "Mini Madeleine's",
	},
	{
		name: "Pumpkin Soup",
		group: "Soups",
		ingredients: [
			{ value: "Pumpkin", slot: "Ingredient 1" },
			{ value: ["Milk", "Buffalo Milk"], slot: "Ingredient 2" },
			{ value: "Onion", slot: "Ingredient 3" },
		],
		baseValue: { value: 1320, unit: "G" },
		effect: "Run Speed Up Lv. 3",
		usedForFestival: "Hearth Day",
		whereToUnlock: "Clara's Calamity request from Clara",
	},
	{
		name: "Vichyssoise Soup",
		group: "Soups",
		ingredients: [
			{ value: "Potato", slot: "Ingredient 1" },
			{ value: "Onion", slot: "Ingredient 2" },
			{ value: ["Milk", "Buffalo Milk"], slot: "Ingredient 3" },
		],
		baseValue: { value: 709, unit: "G" },
		effect: "Run Speed Up Lv. 2",
		whereToUnlock: "Nadine's Bistro",
	},
	{
		name: "Gazpacho Soup",
		group: "Soups",
		ingredients: [
			{ value: "Tomato", slot: "Ingredient 1" },
			{ value: "Garlic", slot: "Ingredient 2" },
			{
				value: ["Bread", "White Bread", "Baguettes", "Focaccia Bread"],
				slot: "Ingredient 3",
			},
		],
		baseValue: { value: 490, unit: "G" },
		effect: "Run Speed Up Lv. 1",
		whereToUnlock: "Café Madeleine",
	},
	{
		name: "Herb Soup",
		group: "Soups",
		ingredients: [
			{ value: ["Mint", "Chamomile", "Lavender"], slot: "Ingredient 1" },
			{ value: ["Mint", "Chamomile", "Lavender"], slot: "Ingredient 2" },
		],
		baseValue: { value: 137, unit: "G" },
		effect: "Run Speed Up Lv. 1",
		usedForFestival: "Hearth Day",
		whereToUnlock: "Available at the start",
	},
	{
		name: "Egg Drop Soup",
		group: "Soups",
		ingredients: [{ value: ["Egg", "Silkie Egg"], slot: "Ingredient 1" }],
		baseValue: { value: 117, unit: "G" },
		effect: "Run Speed Up Lv. 1",
		usedForFestival: "Hearth Day",
		whereToUnlock: "Available at the start",
	},
	{
		name: "Khachapuri",
		group: "Sides",
		ingredients: [
			{ value: "Wheat Flour", slot: "Ingredient 1" },
			{ value: "Cheese+", slot: "Ingredient 2" },
			{ value: "Yogurt+", slot: "Ingredient 3" },
			{ value: "Butter+", slot: "Ingredient 4" },
		],
		baseValue: { value: 10098, unit: "G" },
		effect: "Double Forage",
		whereToUnlock: "A Homemade Meal request from Samir",
	},
	{
		name: "Morel Cream Stew",
		group: "Sides",
		ingredients: [
			{ value: "Morel Mushroom", slot: "Ingredient 1" },
			{ value: "Buffalo Milk", slot: "Ingredient 2" },
			{ value: "Butter (any)", slot: "Ingredient 3" },
			{ value: "Urchin", slot: "Ingredient 4" },
		],
		baseValue: { value: 2592, unit: "G" },
		effect: "Max Stamina Up Lv. 4",
		usedForFestival: "Hearth Day",
		whereToUnlock: "Nadine's Bistro",
	},
	{
		name: "Quiche",
		group: "Sides",
		ingredients: [
			{ value: "Wheat Flour", slot: "Ingredient 1" },
			{ value: "Spinach", slot: "Ingredient 2" },
			{ value: "Pumpkin", slot: "Ingredient 3" },
			{ value: "Mushroom (any)", slot: "Ingredient 4" },
		],
		baseValue: { value: 1892, unit: "G" },
		effect: "Max Stamina Up Lv. 4",
		whereToUnlock: "Main Mushroom request from Mina",
	},
	{
		name: "Fish & Chips",
		group: "Sides",
		ingredients: [
			{
				value: [
					"Yellow Perch",
					"Snakehead",
					"Masu Trout",
					"Char",
					"Salmon",
					"Icefish",
					"Cherry Salmon",
				],
				slot: "Ingredient 1",
			},
			{ value: "Potato", slot: "Ingredient 2" },
			{ value: ["Wheat Flour", "Rice Flour"], slot: "Ingredient 3" },
			{
				value: ["Oil", "Nut Oil", "Herb Oil", "Olive Oil", "Grape Oil"],
				slot: "Ingredient 4",
			},
		],
		baseValue: { value: 1584, unit: "G" },
		effect: "Max Stamina Up Lv. 3",
		whereToUnlock: "Mini Madeleine's",
	},
	{
		name: "Spring Rolls",
		group: "Sides",
		ingredients: [
			{ value: "Wheat Flour", slot: "Ingredient 1" },
			{ value: "Shiitake Mushroom", slot: "Ingredient 2" },
			{ value: "Carrot", slot: "Ingredient 3" },
			{
				value: ["Oil", "Nut Oil", "Herb Oil", "Olive Oil", "Grape Oil"],
				slot: "Ingredient 4",
			},
		],
		baseValue: { value: 1530, unit: "G" },
		effect: "Max Stamina Up Lv. 3",
		whereToUnlock: "Clara's Diner",
	},
	{
		name: "Steamed Bun",
		group: "Sides",
		ingredients: [
			{ value: "Wheat Flour", slot: "Ingredient 1" },
			{ value: "Napa Cabbage", slot: "Ingredient 2" },
			{ value: "Shiitake Mushroom", slot: "Ingredient 3" },
			{ value: "Green Onion", slot: "Ingredient 4" },
		],
		baseValue: { value: 1377, unit: "G" },
		effect: "Max Stamina Up Lv. 3",
		whereToUnlock: "Mini Madeleine's",
	},
	{
		name: "Gyoza",
		group: "Sides",
		ingredients: [
			{ value: "Wheat Flour", slot: "Ingredient 1" },
			{ value: "Cabbage", slot: "Ingredient 2" },
			{
				value: ["Oil", "Nut Oil", "Herb Oil", "Olive Oil", "Grape Oil"],
				slot: "Ingredient 3",
			},
		],
		baseValue: { value: 1353, unit: "G" },
		effect: "Max Stamina Up Lv. 3",
		whereToUnlock: "Clara's Diner",
	},
	{
		name: "Stir-Fried Vegetables",
		group: "Sides",
		ingredients: [
			{ value: "Cabbage", slot: "Ingredient 1" },
			{ value: "Napa Cabbage", slot: "Ingredient 2" },
		],
		baseValue: { value: 1276, unit: "G" },
		effect: "Max Stamina Up Lv. 3",
		whereToUnlock: "Clara's Diner",
	},
	{
		name: "Stuffed Cabbage",
		group: "Sides",
		ingredients: [
			{ value: "Cabbage", slot: "Ingredient 1" },
			{ value: "Carrot", slot: "Ingredient 2" },
		],
		baseValue: { value: 1213, unit: "G" },
		effect: "Max Stamina Up Lv. 3",
		whereToUnlock: "Famed Foodie request from Madeleine",
	},
	{
		name: "Scones",
		group: "Sides",
		ingredients: [
			{ value: "Wheat Flour", slot: "Ingredient 1" },
			{ value: "Butter (any)", slot: "Ingredient 2" },
			{ value: ["Milk", "Buffalo Milk"], slot: "Ingredient 3" },
		],
		baseValue: { value: 1155, unit: "G" },
		effect: "Max Stamina Up Lv. 3",
		whereToUnlock: "Café Madeleine",
	},
	{
		name: "Galette",
		group: "Sides",
		ingredients: [
			{ value: "Buckwheat Flour", slot: "Ingredient 1" },
			{ value: "Potato", slot: "Ingredient 2" },
			{
				value: ["Oil", "Nut Oil", "Herb Oil", "Olive Oil", "Grape Oil"],
				slot: "Ingredient 3",
			},
		],
		baseValue: { value: 1122, unit: "G" },
		effect: "Max Stamina Up Lv. 3",
		whereToUnlock: "Mini Madeleine's",
	},
	{
		name: "Buttered Roll",
		group: "Sides",
		ingredients: [
			{ value: "Wheat Flour", slot: "Ingredient 1" },
			{ value: ["Egg", "Silkie Egg"], slot: "Ingredient 2" },
			{ value: "Butter (any)", slot: "Ingredient 3" },
		],
		baseValue: { value: 1056, unit: "G" },
		effect: "Max Stamina Up Lv. 3",
		whereToUnlock: "Café Madeleine",
	},
	{
		name: "Chili con Carne",
		group: "Sides",
		ingredients: [
			{ value: "Tomato", slot: "Ingredient 1" },
			{ value: "Soybean", slot: "Ingredient 2" },
			{ value: "Chili Pepper", slot: "Ingredient 3" },
			{ value: "Pepper", slot: "Ingredient 4" },
		],
		baseValue: { value: 911, unit: "G" },
		effect: "Max Stamina Up Lv. 2",
		usedForFestival: "Hearth Day",
		whereToUnlock: "Nadine's Bistro",
	},
	{
		name: "Sautéed Turnips",
		group: "Sides",
		ingredients: [
			{ value: "Turnip", slot: "Ingredient 1" },
			{ value: "Butter (any)", slot: "Ingredient 2" },
		],
		baseValue: { value: 882, unit: "G" },
		effect: "Max Stamina Up Lv. 2",
		whereToUnlock: "Café Madeleine",
	},
	{
		name: "Focaccia Bread",
		group: "Sides",
		ingredients: [
			{ value: "Wheat Flour", slot: "Ingredient 1" },
			{ value: "Olive Oil", slot: "Ingredient 2" },
		],
		baseValue: { value: 843, unit: "G" },
		effect: "Max Stamina Up Lv. 2",
		whereToUnlock: "Bookshelves in Lloyd's House",
	},
	{
		name: "Freeze-Dried Tofu",
		group: "Sides",
		ingredients: [
			{ value: "Tofu", slot: "Ingredient 1" },
			{ value: "Soy Sauce", slot: "Ingredient 2" },
			{
				value: ["Oil", "Nut Oil", "Herb Oil", "Olive Oil", "Grape Oil"],
				slot: "Ingredient 3",
			},
		],
		baseValue: { value: 824, unit: "G" },
		effect: "Max Stamina Up Lv. 2",
		whereToUnlock: "Clara's Diner",
	},
	{
		name: "Lightly Fried Tofu",
		group: "Sides",
		ingredients: [
			{ value: "Tofu", slot: "Ingredient 1" },
			{ value: ["Wheat Flour", "Rice Flour"], slot: "Ingredient 2" },
			{
				value: ["Oil", "Nut Oil", "Herb Oil", "Olive Oil", "Grape Oil"],
				slot: "Ingredient 3",
			},
		],
		baseValue: { value: 809, unit: "G" },
		effect: "Max Stamina Up Lv. 2",
		whereToUnlock: "Clara's Diner",
	},
	{
		name: "Rolled Egg",
		group: "Sides",
		ingredients: [
			{ value: ["Egg", "Silkie Egg"], slot: "Ingredient 1" },
			{ value: "Soy Sauce", slot: "Ingredient 2" },
			{ value: "Sugar", slot: "Ingredient 3" },
		],
		baseValue: { value: 801, unit: "G" },
		effect: "Max Stamina Up Lv. 2",
		whereToUnlock: "Clara's Diner",
	},
	{
		name: "Steamed Egg Custard",
		group: "Sides",
		ingredients: [
			{ value: ["Egg", "Silkie Egg"], slot: "Ingredient 1" },
			{ value: "Shiitake Mushroom", slot: "Ingredient 2" },
			{ value: "Fish Cake", slot: "Ingredient 3" },
		],
		baseValue: { value: 747, unit: "G" },
		effect: "Max Stamina Up Lv. 2",
		whereToUnlock: "Clara's Diner",
	},
	{
		name: "Soy Okara",
		group: "Sides",
		ingredients: [
			{ value: "Tofu", slot: "Ingredient 1" },
			{ value: "Carrot", slot: "Ingredient 2" },
		],
		baseValue: { value: 743, unit: "G" },
		effect: "Max Stamina Up Lv. 2",
		whereToUnlock: "Clara's Diner",
	},
	{
		name: "Buttered Potato",
		group: "Sides",
		ingredients: [
			{ value: "Potato", slot: "Ingredient 1" },
			{ value: "Butter (any)", slot: "Ingredient 2" },
		],
		baseValue: { value: 677, unit: "G" },
		effect: "Max Stamina Up Lv. 2",
		whereToUnlock: "Count on Coach! request from Freya",
	},
	{
		name: "Baguettes",
		group: "Sides",
		ingredients: [
			{ value: "Wheat Flour", slot: "Ingredient 1" },
			{ value: "Salt", slot: "Ingredient 2" },
		],
		baseValue: { value: 662, unit: "G" },
		effect: "Max Stamina Up Lv. 2",
		whereToUnlock: "Mini Madeleine's",
	},
	{
		name: "Hash Browns",
		group: "Sides",
		ingredients: [
			{ value: "Potato", slot: "Ingredient 1" },
			{ value: "Wheat Flour", slot: "Ingredient 2" },
			{
				value: ["Oil", "Nut Oil", "Herb Oil", "Olive Oil", "Grape Oil"],
				slot: "Ingredient 3",
			},
		],
		baseValue: { value: 632, unit: "G" },
		effect: "Max Stamina Up Lv. 2",
		whereToUnlock: "Mini Madeleine's",
	},
	{
		name: "Steamed Muffin",
		group: "Sides",
		ingredients: [
			{ value: "Wheat Flour", slot: "Ingredient 1" },
			{ value: ["Egg", "Silkie Egg"], slot: "Ingredient 2" },
			{ value: "Sweet Potato", slot: "Ingredient 3" },
		],
		baseValue: { value: 609, unit: "G" },
		effect: "Max Stamina Up Lv. 2",
		whereToUnlock:
			"Bug Collector title, Generous Bug Catcher title, Clara's Diner",
	},
	{
		name: "Sautéed Cauliflower",
		group: "Sides",
		ingredients: [{ value: "Cauliflower", slot: "Ingredient 1" }],
		baseValue: { value: 602, unit: "G" },
		effect: "Max Stamina Up Lv. 2",
		whereToUnlock: "Mini Madeleine's",
	},
	{
		name: "Broccoli & Garlic Sauté",
		group: "Sides",
		ingredients: [
			{ value: "Broccoli", slot: "Ingredient 1" },
			{ value: "Garlic", slot: "Ingredient 2" },
			{
				value: ["Oil", "Nut Oil", "Herb Oil", "Olive Oil", "Grape Oil"],
				slot: "Ingredient 3",
			},
		],
		baseValue: { value: 563, unit: "G" },
		effect: "Max Stamina Up Lv. 2",
		whereToUnlock: "Nadine's Bistro",
	},
	{
		name: "Chilled Tofu",
		group: "Sides",
		ingredients: [
			{ value: "Tofu", slot: "Ingredient 1" },
			{ value: "Soy Sauce", slot: "Ingredient 2" },
		],
		baseValue: { value: 458, unit: "G" },
		effect: "Max Stamina Up Lv. 1",
		whereToUnlock: "Clara's Diner",
	},
	{
		name: "Potato Pancakes",
		group: "Sides",
		ingredients: [
			{ value: "Potato", slot: "Ingredient 1" },
			{ value: "Wheat Flour", slot: "Ingredient 2" },
			{ value: ["Egg", "Silkie Egg"], slot: "Ingredient 3" },
		],
		baseValue: { value: 429, unit: "G" },
		effect: "Max Stamina Up Lv. 1",
		whereToUnlock: "Café Madeleine",
	},
	{
		name: "Corn Flakes Cereal",
		group: "Sides",
		ingredients: [
			{ value: "Corn", slot: "Ingredient 1" },
			{ value: ["Milk", "Buffalo Milk"], slot: "Ingredient 2" },
		],
		baseValue: { value: 403, unit: "G" },
		effect: "Max Stamina Up Lv. 1",
		whereToUnlock: "Clara's Diner",
	},
	{
		name: "Fried Egg",
		group: "Sides",
		ingredients: [
			{ value: ["Egg", "Silkie Egg"], slot: "Ingredient 1" },
			{
				value: ["Oil", "Nut Oil", "Herb Oil", "Olive Oil", "Grape Oil"],
				slot: "Ingredient 2",
			},
		],
		baseValue: { value: 396, unit: "G" },
		effect: "Max Stamina Up Lv. 1",
		whereToUnlock: "Café Madeleine",
	},
	{
		name: "Fried Tofu",
		group: "Sides",
		ingredients: [{ value: "Tofu", slot: "Ingredient 1" }],
		baseValue: { value: 267, unit: "G" },
		effect: "Max Stamina Up Lv. 1",
		whereToUnlock: "Nadine's Bistro",
	},
	{
		name: "Miso Glazed Eggplant",
		group: "Sides",
		ingredients: [
			{ value: "Eggplant", slot: "Ingredient 1" },
			{ value: "Miso", slot: "Ingredient 2" },
		],
		baseValue: { value: 246, unit: "G" },
		effect: "Max Stamina Up Lv. 1",
		whereToUnlock: "Nadine's Bistro",
	},
	{
		name: "Toast",
		group: "Sides",
		ingredients: [{ value: ["Bread", "White Bread"], slot: "Ingredient 1" }],
		baseValue: { value: 234, unit: "G" },
		effect: "Max Stamina Up Lv. 1",
		whereToUnlock: "Bookshelves in June's House",
	},
	{
		name: "Tofu",
		group: "Sides",
		ingredients: [
			{ value: "Soybean", slot: "Ingredient 1" },
			{ value: "Soy Milk", slot: "Ingredient 2" },
		],
		baseValue: { value: 205, unit: "G" },
		effect: "Max Stamina Up Lv. 1",
		whereToUnlock: "Mini Madeleine's",
	},
	{
		name: "Fried Mushrooms",
		group: "Sides",
		ingredients: [{ value: "Mushroom (any)", slot: "Ingredient 1" }],
		baseValue: { value: 195, unit: "G" },
		effect: "Max Stamina Up Lv. 1",
		whereToUnlock: "Felix’s Fixings (Autumn)",
	},
	{
		name: "Boiled Egg",
		group: "Sides",
		ingredients: [{ value: ["Egg", "Silkie Egg"], slot: "Ingredient 1" }],
		baseValue: { value: 117, unit: "G" },
		effect: "Max Stamina Up Lv. 1",
		whereToUnlock: "Available at the start",
	},
	{
		name: "Tofu Skin",
		group: "Sides",
		ingredients: [{ value: "Soy Milk", slot: "Ingredient 1" }],
		baseValue: { value: 111, unit: "G" },
		effect: "Max Stamina Up Lv. 1",
		whereToUnlock: "Clara's Diner",
	},
	{
		name: "Shumai Dumplings",
		group: "Sides",
		ingredients: [
			{ value: "Wheat Flour", slot: "Ingredient 1" },
			{ value: "Onion", slot: "Ingredient 2" },
			{
				value: [
					"Bluegill",
					"Willow Shiner",
					"Killifish",
					"Stone Moroko",
					"Pond Smelt",
					"Sweetfish",
					"Eel",
					"Marbled Eel",
					"Goldfish",
					"Crucian Carp",
				],
				slot: "Ingredient 3",
			},
		],
		baseValue: { value: 924, unit: "G" },
		effect: "Rod Durability Up Lv. 2",
		whereToUnlock: "Reeling in a Meal request from Sonia",
	},
	{
		name: "Sashimi",
		group: "Sides",
		ingredients: [
			{
				value: [
					"Amur Minnow",
					"Dace",
					"Pale Chub",
					"Sculpin",
					"Dark Chub",
					"Bitterling",
					"Tamoroko",
					"Rainbow Trout",
					"Silver Carp",
					"Basa",
				],
				slot: "Ingredient 1",
			},
		],
		baseValue: { value: 195, unit: "G" },
		effect: "Rod Durability Up Lv. 1",
		whereToUnlock: "Available at the start",
	},
	{
		name: "Fish Cake",
		group: "Sides",
		ingredients: [
			{
				value: [
					"Amur Minnow",
					"Dace",
					"Pale Chub",
					"Sculpin",
					"Dark Chub",
					"Bitterling",
					"Tamoroko",
					"Rainbow Trout",
					"Silver Carp",
					"Basa",
				],
				slot: "Ingredient 1",
			},
		],
		baseValue: { value: 195, unit: "G" },
		effect: "Rod Durability Up Lv. 1",
		whereToUnlock: "Bottled Nuts Wanted request from Nadine",
	},
	{
		name: "Babaocai",
		group: "Sides",
		ingredients: [
			{ value: "Napa Cabbage", slot: "Ingredient 1" },
			{ value: "Carrot", slot: "Ingredient 2" },
			{ value: "Green Bell Pepper", slot: "Ingredient 3" },
			{ value: "Mushroom (any)", slot: "Ingredient 4" },
		],
		baseValue: { value: 1509, unit: "G" },
		effect: "Watering Rare Crop % Lv. 3",
		whereToUnlock: "Hydrator title, Nadine's Bistro",
	},
	{
		name: "Grilled Corn",
		group: "Sides",
		ingredients: [
			{ value: "Corn", slot: "Ingredient 1" },
			{ value: "Soy Sauce", slot: "Ingredient 2" },
			{ value: "Sugar", slot: "Ingredient 3" },
		],
		baseValue: { value: 886, unit: "G" },
		effect: "Watering Rare Crop % Lv. 2",
		whereToUnlock: "Felix’s Fixings (Summer)",
	},
	{
		name: "Curry Bun",
		group: "Sides",
		ingredients: [
			{ value: "Wheat Flour", slot: "Ingredient 1" },
			{ value: "Curry Powder", slot: "Ingredient 2" },
			{ value: "Onion", slot: "Ingredient 3" },
			{ value: "Carrot", slot: "Ingredient 4" },
		],
		baseValue: { value: 1920, unit: "G" },
		effect: "Chat Friendship Boost Lv. 4",
		whereToUnlock: "Clara's Diner",
	},
	{
		name: "Cheese Croquettes",
		group: "Sides",
		ingredients: [
			{ value: "Potato", slot: "Ingredient 1" },
			{ value: ["Breadcrumbs", "White Breadcrumbs"], slot: "Ingredient 2" },
			{
				value: ["Oil", "Nut Oil", "Herb Oil", "Olive Oil", "Grape Oil"],
				slot: "Ingredient 3",
			},
			{ value: "Cheese (any)", slot: "Ingredient 4" },
		],
		baseValue: { value: 1844, unit: "G" },
		effect: "Chat Friendship Boost Lv. 4",
		whereToUnlock: "Nadine's Bistro",
	},
	{
		name: "Cheese Bun",
		group: "Sides",
		ingredients: [
			{ value: "Wheat Flour", slot: "Ingredient 1" },
			{ value: "Cheese (any)", slot: "Ingredient 2" },
			{ value: "Buffalo Milk", slot: "Ingredient 3" },
		],
		baseValue: { value: 1320, unit: "G" },
		effect: "Chat Friendship Boost Lv. 3",
		whereToUnlock: "Mini Madeleine's",
	},
	{
		name: "Cream Croquettes",
		group: "Sides",
		ingredients: [
			{ value: "Potato", slot: "Ingredient 1" },
			{ value: ["Breadcrumbs", "White Breadcrumbs"], slot: "Ingredient 2" },
			{
				value: ["Oil", "Nut Oil", "Herb Oil", "Olive Oil", "Grape Oil"],
				slot: "Ingredient 3",
			},
			{ value: ["Milk", "Buffalo Milk"], slot: "Ingredient 4" },
		],
		baseValue: { value: 1098, unit: "G" },
		effect: "Chat Friendship Boost Lv. 3",
		whereToUnlock: "Nadine's Bistro",
	},
	{
		name: "Stew",
		group: "Sides",
		ingredients: [
			{ value: "Wheat Flour", slot: "Ingredient 1" },
			{ value: ["Milk", "Buffalo Milk"], slot: "Ingredient 2" },
			{
				value: [
					"Potato",
					"Asparagus",
					"Carrot",
					"Cabbage",
					"Turnip",
					"Cauliflower",
				],
				slot: "Ingredient 3",
			},
		],
		baseValue: { value: 770, unit: "G" },
		effect: "Chat Friendship Boost Lv. 2",
		usedForFestival: "Hearth Day",
		whereToUnlock: "Nadine's Bistro",
	},
	{
		name: "Croquettes",
		group: "Sides",
		ingredients: [
			{ value: "Potato", slot: "Ingredient 1" },
			{ value: ["Breadcrumbs", "White Breadcrumbs"], slot: "Ingredient 2" },
			{
				value: ["Oil", "Nut Oil", "Herb Oil", "Olive Oil", "Grape Oil"],
				slot: "Ingredient 3",
			},
		],
		baseValue: { value: 709, unit: "G" },
		effect: "Chat Friendship Boost Lv. 2",
		whereToUnlock: "Clara's Diner",
	},
	{
		name: "French Toast",
		group: "Sides",
		ingredients: [
			{ value: ["Bread", "White Bread"], slot: "Ingredient 1" },
			{ value: ["Egg", "Silkie Egg"], slot: "Ingredient 2" },
			{ value: ["Milk", "Buffalo Milk"], slot: "Ingredient 3" },
		],
		baseValue: { value: 647, unit: "G" },
		effect: "Chat Friendship Boost Lv. 2",
		whereToUnlock: "Nadine's Bistro",
	},
	{
		name: "Popcorn",
		group: "Sides",
		ingredients: [
			{ value: "Corn", slot: "Ingredient 1" },
			{
				value: ["Oil", "Nut Oil", "Herb Oil", "Olive Oil", "Grape Oil"],
				slot: "Ingredient 2",
			},
		],
		baseValue: { value: 508, unit: "G" },
		effect: "Chat Friendship Boost Lv. 2",
		usedForFestival: "Pumpkin Festival",
		whereToUnlock: "Neighborly title, Mini Madeleine's",
	},
	{
		name: "French Fries",
		group: "Sides",
		ingredients: [
			{ value: "Potato", slot: "Ingredient 1" },
			{
				value: ["Oil", "Nut Oil", "Herb Oil", "Olive Oil", "Grape Oil"],
				slot: "Ingredient 2",
			},
		],
		baseValue: { value: 355, unit: "G" },
		effect: "Chat Friendship Boost Lv. 1",
		whereToUnlock: "Mini Madeleine's",
	},
	{
		name: "Poached Egg",
		group: "Sides",
		ingredients: [
			{ value: ["Egg", "Silkie Egg"], slot: "Ingredient 1" },
			{ value: "Soy Sauce", slot: "Ingredient 2" },
		],
		baseValue: { value: 301, unit: "G" },
		effect: "Chat Friendship Boost Lv. 1",
		whereToUnlock: "Café Madeleine",
	},
	{
		name: "Baked Sweet Potato",
		group: "Sides",
		ingredients: [{ value: "Sweet Potato", slot: "Ingredient 1" }],
		baseValue: { value: 202, unit: "G" },
		effect: "Chat Friendship Boost Lv. 1",
		whereToUnlock: "Felix’s Fixings (Autumn)",
	},
	{
		name: "Bread",
		group: "Sides",
		ingredients: [{ value: "Wheat Flour", slot: "Ingredient 1" }],
		baseValue: { value: 195, unit: "G" },
		effect: "None",
		whereToUnlock:
			"Café Madeleine, Mini Madeleine's, Nadine's Bistro, Clara's Diner",
	},
	{
		name: "White Bread",
		group: "Sides",
		ingredients: [{ value: "Rice Flour", slot: "Ingredient 1" }],
		baseValue: { value: 182, unit: "G" },
		effect: "None",
		whereToUnlock: "Nadine's Bistro",
	},
	{
		name: "Cooked Rice",
		group: "Sides",
		ingredients: [{ value: "Rice", slot: "Ingredient 1" }],
		baseValue: { value: 91, unit: "G" },
		effect: "None",
		whereToUnlock:
			"Café Madeleine, Mini Madeleine's, Nadine's Bistro, Clara's Diner",
	},
	{
		name: "Ultimate Curry",
		group: "Main Dishes",
		ingredients: [
			{ value: "Supreme Curry", slot: "Ingredient 1" },
			{ value: "Giant Tomato", slot: "Ingredient 2" },
			{ value: "Curled Chili Pepper", slot: "Ingredient 3" },
			{ value: "Yogurt+", slot: "Ingredient 4" },
		],
		baseValue: { value: 12353, unit: "G" },
		effect: "None",
		whereToUnlock: "Out of the Extra-Ordinary request from Madeleine",
	},
	{
		name: "Fried Rice Noodles",
		group: "Main Dishes",
		ingredients: [
			{ value: "Rice Flour", slot: "Ingredient 1" },
			{ value: "Monarch Mushroom", slot: "Ingredient 2" },
			{ value: "Cabbage", slot: "Ingredient 3" },
			{ value: "Carrot", slot: "Ingredient 4" },
		],
		baseValue: { value: 7508, unit: "G" },
		effect: "None",
		whereToUnlock: "Remarkable Mushrooms request from Nadine",
	},
	{
		name: "Farmer's Breakfast",
		group: "Main Dishes",
		ingredients: [
			{ value: "Potato", slot: "Ingredient 1" },
			{ value: "Onion", slot: "Ingredient 2" },
			{ value: "Cheese+", slot: "Ingredient 3" },
			{ value: "Mayonnaise+", slot: "Ingredient 4" },
		],
		baseValue: { value: 6957, unit: "G" },
		effect: "None",
		whereToUnlock: "Celebrated Cuisine request from Madeleine",
	},
	{
		name: "Supreme Curry",
		group: "Main Dishes",
		ingredients: [
			{ value: "Curry Rice", slot: "Ingredient 1" },
			{ value: "Star Potato", slot: "Ingredient 2" },
			{ value: "Three-Forked Carrot", slot: "Ingredient 3" },
		],
		baseValue: { value: 3724, unit: "G" },
		effect: "None",
		whereToUnlock: "Win the Cook-Off! Festival",
	},
	{
		name: "Pizzoccheri",
		group: "Main Dishes",
		ingredients: [
			{ value: "Buckwheat Flour", slot: "Ingredient 1" },
			{ value: "Cheese (any)", slot: "Ingredient 2" },
			{ value: "Cabbage", slot: "Ingredient 3" },
			{ value: "Potato", slot: "Ingredient 4" },
		],
		baseValue: { value: 2784, unit: "G" },
		effect: "None",
		whereToUnlock: "Nadine's Bistro",
	},
	{
		name: "Tempura Soba",
		group: "Main Dishes",
		ingredients: [
			{ value: "Buckwheat Flour", slot: "Ingredient 1" },
			{ value: "Tempura", slot: "Ingredient 2" },
		],
		baseValue: { value: 2641, unit: "G" },
		effect: "None",
		usedForFestival: "Hearth Day",
		whereToUnlock: "Clara's Diner",
	},
	{
		name: "Milk Hot Pot",
		group: "Main Dishes",
		ingredients: [
			{ value: "Milk+", slot: "Ingredient 1" },
			{ value: "Carrot", slot: "Ingredient 2" },
			{ value: "Napa Cabbage", slot: "Ingredient 3" },
			{ value: "Spinach", slot: "Ingredient 4" },
		],
		baseValue: { value: 2640, unit: "G" },
		effect: "None",
		usedForFestival: "Hearth Day",
		whereToUnlock: "Mini Madeleine's",
	},
	{
		name: "Macaroni & Cheese",
		group: "Main Dishes",
		ingredients: [
			{ value: "Wheat Flour", slot: "Ingredient 1" },
			{ value: "Cheese (any)", slot: "Ingredient 2" },
			{ value: "Butter (any)", slot: "Ingredient 3" },
			{ value: "Mayonnaise (any)", slot: "Ingredient 4" },
		],
		baseValue: { value: 2592, unit: "G" },
		effect: "None",
		whereToUnlock: "Nadine's Bistro",
	},
	{
		name: "Hot Pot",
		group: "Main Dishes",
		ingredients: [
			{ value: "Daikon Radish", slot: "Ingredient 1" },
			{ value: "Napa Cabbage", slot: "Ingredient 2" },
			{ value: "Green Onion", slot: "Ingredient 3" },
			{
				value: [
					"Nile Perch",
					"Salmon",
					"Masu Trout",
					"Cherry Salmon",
					"Brown Trout",
					"Yellow Perch",
					"Sweetfish",
				],
				slot: "Ingredient 4",
			},
		],
		baseValue: { value: 2487, unit: "G" },
		effect: "None",
		usedForFestival: "Hearth Day",
		whereToUnlock: "Clara's Diner",
	},
	{
		name: "Ukha",
		group: "Main Dishes",
		ingredients: [
			{
				value: [
					"Nile Perch",
					"Salmon",
					"Masu Trout",
					"Cherry Salmon",
					"Brown Trout",
					"Yellow Perch",
					"Sweetfish",
				],
				slot: "Ingredient 1",
			},
			{ value: "Carrot", slot: "Ingredient 2" },
			{ value: "Potato", slot: "Ingredient 3" },
			{ value: "Onion", slot: "Ingredient 4" },
		],
		baseValue: { value: 2324, unit: "G" },
		effect: "None",
		usedForFestival: "Hearth Day",
		whereToUnlock: "Nadine's Bistro",
	},
	{
		name: "Mushroom Polenta",
		group: "Main Dishes",
		ingredients: [
			{ value: "Mushroom (any)", slot: "Ingredient 1" },
			{ value: "Corn", slot: "Ingredient 2" },
			{ value: "Butter (any)", slot: "Ingredient 3" },
			{ value: "Cheese (any)", slot: "Ingredient 4" },
		],
		baseValue: { value: 2295, unit: "G" },
		effect: "None",
		whereToUnlock: "Nadine's Bistro",
	},
	{
		name: "Tempura Udon",
		group: "Main Dishes",
		ingredients: [
			{ value: "Wheat Flour", slot: "Ingredient 1" },
			{ value: "Tempura", slot: "Ingredient 2" },
		],
		baseValue: { value: 2188, unit: "G" },
		effect: "None",
		usedForFestival: "Hearth Day",
		whereToUnlock: "Clara's Diner",
	},
	{
		name: "Marinated Fish",
		group: "Main Dishes",
		ingredients: [
			{
				value: [
					"Nile Perch",
					"Salmon",
					"Masu Trout",
					"Cherry Salmon",
					"Brown Trout",
					"Yellow Perch",
					"Sweetfish",
				],
				slot: "Ingredient 1",
			},
			{ value: "Onion", slot: "Ingredient 2" },
			{ value: "Vinegar", slot: "Ingredient 3" },
			{ value: "Lemon", slot: "Ingredient 4" },
		],
		baseValue: { value: 2160, unit: "G" },
		effect: "None",
		whereToUnlock: "Mood Improver request from Mina",
	},
	{
		name: "Tempura Rice Bowl",
		group: "Main Dishes",
		ingredients: [
			{ value: "Tempura", slot: "Ingredient 1" },
			{ value: "Cooked Rice", slot: "Ingredient 2" },
		],
		baseValue: { value: 2089, unit: "G" },
		effect: "None",
		whereToUnlock: "Clara's Diner",
	},
	{
		name: "Raclette Cheese",
		group: "Main Dishes",
		ingredients: [
			{ value: "Cheese (any)", slot: "Ingredient 1" },
			{ value: "Corn", slot: "Ingredient 2" },
			{ value: "Carrot", slot: "Ingredient 3" },
			{ value: "Broccoli", slot: "Ingredient 4" },
		],
		baseValue: { value: 1901, unit: "G" },
		effect: "None",
		whereToUnlock: "Nadine's Bistro",
	},
	{
		name: "Pasta Salad",
		group: "Main Dishes",
		ingredients: [
			{ value: "Pasta", slot: "Ingredient 1" },
			{ value: "Mixed Salad", slot: "Ingredient 2" },
			{ value: "Mayonnaise (any)", slot: "Ingredient 3" },
		],
		baseValue: { value: 1817, unit: "G" },
		effect: "None",
		whereToUnlock: "A Selfish Request request from Jules",
	},
	{
		name: "Matsutake Rice",
		group: "Main Dishes",
		ingredients: [
			{ value: "Rice", slot: "Ingredient 1" },
			{ value: "Matsutake Mushroom", slot: "Ingredient 2" },
			{ value: "Soy Sauce", slot: "Ingredient 3" },
		],
		baseValue: { value: 1760, unit: "G" },
		effect: "None",
		whereToUnlock: "Clara's Diner",
	},
	{
		name: "Gratin",
		group: "Main Dishes",
		ingredients: [
			{ value: "Wheat Flour", slot: "Ingredient 1" },
			{ value: "Cheese (any)", slot: "Ingredient 2" },
			{ value: "Mayonnaise (any)", slot: "Ingredient 3" },
		],
		baseValue: { value: 1568, unit: "G" },
		effect: "None",
		whereToUnlock: "Milk Par Excellence request from Nadine",
	},
	{
		name: "Spaghetti Soup",
		group: "Main Dishes",
		ingredients: [
			{ value: "Pasta", slot: "Ingredient 1" },
			{ value: "Tomato", slot: "Ingredient 2" },
			{
				value: [
					"Grayling",
					"Bighead Carp",
					"Nile Perch",
					"Barbel Steed",
					"Three-Lips Carp",
					"Brown Trout",
					"Black Bass",
					"Mugitsuku",
				],
				slot: "Ingredient 3",
			},
			{
				value: ["Oil", "Nut Oil", "Herb Oil", "Olive Oil", "Grape Oil"],
				slot: "Ingredient 4",
			},
		],
		baseValue: { value: 1568, unit: "G" },
		effect: "None",
		usedForFestival: "Hearth Day",
		whereToUnlock: "Café Madeleine",
	},
	{
		name: "Risotto",
		group: "Main Dishes",
		ingredients: [
			{ value: "Rice", slot: "Ingredient 1" },
			{ value: "Cheese (any)", slot: "Ingredient 2" },
			{ value: "Tomato", slot: "Ingredient 3" },
			{ value: "Onion", slot: "Ingredient 4" },
		],
		baseValue: { value: 1552, unit: "G" },
		effect: "None",
		whereToUnlock: "Café Madeleine",
	},
	{
		name: "Carpaccio",
		group: "Main Dishes",
		ingredients: [
			{
				value: [
					"Yellow Perch",
					"Snakehead",
					"Masu Trout",
					"Char",
					"Salmon",
					"Icefish",
					"Cherry Salmon",
				],
				slot: "Ingredient 1",
			},
			{ value: "Onion", slot: "Ingredient 2" },
			{ value: "Vinegar", slot: "Ingredient 3" },
		],
		baseValue: { value: 1469, unit: "G" },
		effect: "None",
		whereToUnlock: "Nadine's Bistro",
	},
	{
		name: "Cheese Fondue",
		group: "Main Dishes",
		ingredients: [
			{ value: "Cheese (any)", slot: "Ingredient 1" },
			{
				value: ["Bread", "White Bread", "Baguettes", "Focaccia Bread"],
				slot: "Ingredient 2",
			},
			{
				value: [
					"Broccoli",
					"Potato",
					"Asparagus",
					"Red Bell Pepper",
					"Carrot",
					"Common Mushroom",
					"Pumpkin",
				],
				slot: "Ingredient 3",
			},
		],
		baseValue: { value: 1452, unit: "G" },
		effect: "None",
		whereToUnlock: "Nadine's Bistro",
	},
	{
		name: "Mushroom Pasta",
		group: "Main Dishes",
		ingredients: [
			{ value: "Pasta", slot: "Ingredient 1" },
			{ value: "Mushroom (any)", slot: "Ingredient 2" },
			{ value: "Butter (any)", slot: "Ingredient 3" },
		],
		baseValue: { value: 1449, unit: "G" },
		effect: "None",
		whereToUnlock: "Café Madeleine",
	},
	{
		name: "Inari Sushi",
		group: "Main Dishes",
		ingredients: [
			{ value: "Cooked Rice", slot: "Ingredient 1" },
			{ value: "Fried Tofu", slot: "Ingredient 2" },
			{ value: "Vinegar", slot: "Ingredient 3" },
			{ value: "Sugar", slot: "Ingredient 4" },
		],
		baseValue: { value: 1437, unit: "G" },
		effect: "None",
		whereToUnlock: "Clara's Diner",
	},
	{
		name: "Fried Udon",
		group: "Main Dishes",
		ingredients: [
			{ value: "Wheat Flour", slot: "Ingredient 1" },
			{ value: "Cabbage", slot: "Ingredient 2" },
			{ value: "Green Bell Pepper", slot: "Ingredient 3" },
			{ value: "Soy Sauce", slot: "Ingredient 4" },
		],
		baseValue: { value: 1437, unit: "G" },
		effect: "None",
		whereToUnlock: "Clara's Diner",
	},
	{
		name: "Spicy Curry",
		group: "Main Dishes",
		ingredients: [
			{ value: "Cooked Rice", slot: "Ingredient 1" },
			{ value: "Curry Powder", slot: "Ingredient 2" },
			{ value: "Spice", slot: "Ingredient 3" },
			{ value: ["Potato", "Carrot", "Onion"], slot: "Ingredient 4" },
		],
		baseValue: { value: 1424, unit: "G" },
		effect: "None",
		whereToUnlock: "Fondue Fancy! request from Sophie",
	},
	{
		name: "Omelet Rice",
		group: "Main Dishes",
		ingredients: [
			{ value: "Omelet", slot: "Ingredient 1" },
			{ value: "Cooked Rice", slot: "Ingredient 2" },
		],
		baseValue: { value: 1410, unit: "G" },
		effect: "None",
		whereToUnlock: "Bookshelves in Gabriel's House",
	},
	{
		name: "Spaghetti Peperoncino",
		group: "Main Dishes",
		ingredients: [
			{ value: "Pasta", slot: "Ingredient 1" },
			{ value: "Chili Pepper", slot: "Ingredient 2" },
			{ value: "Garlic", slot: "Ingredient 3" },
			{
				value: ["Oil", "Nut Oil", "Herb Oil", "Olive Oil", "Grape Oil"],
				slot: "Ingredient 4",
			},
		],
		baseValue: { value: 1410, unit: "G" },
		effect: "None",
		whereToUnlock: "Nadine's Bistro",
	},
	{
		name: "Seaweed Curry",
		group: "Main Dishes",
		ingredients: [
			{ value: "Cooked Rice", slot: "Ingredient 1" },
			{ value: "Curry Powder", slot: "Ingredient 2" },
			{ value: "Seaweed", slot: "Ingredient 3" },
			{ value: ["Potato", "Carrot", "Onion"], slot: "Ingredient 4" },
		],
		baseValue: { value: 1388, unit: "G" },
		effect: "None",
		whereToUnlock: "Clara's Diner",
	},
	{
		name: "Jam-Filled Bun",
		group: "Main Dishes",
		ingredients: [
			{ value: "Wheat Flour", slot: "Ingredient 1" },
			{
				value: ["Apple Jam", "Strawberry Jam", "Grape Jam", "Blueberry Jam"],
				slot: "Ingredient 2",
			},
		],
		baseValue: { value: 1339, unit: "G" },
		effect: "None",
		whereToUnlock: "Café Madeleine",
	},
	{
		name: "Milk Curry",
		group: "Main Dishes",
		ingredients: [
			{ value: "Cooked Rice", slot: "Ingredient 1" },
			{ value: "Curry Powder", slot: "Ingredient 2" },
			{ value: ["Milk", "Buffalo Milk"], slot: "Ingredient 3" },
			{ value: ["Potato", "Carrot", "Onion"], slot: "Ingredient 4" },
		],
		baseValue: { value: 1334, unit: "G" },
		effect: "None",
		whereToUnlock: "Nadine's Bistro",
	},
	{
		name: "Burgundy Fondue",
		group: "Main Dishes",
		ingredients: [
			{ value: "Olive Oil", slot: "Ingredient 1" },
			{
				value: ["Bread", "White Bread", "Baguettes", "Focaccia Bread"],
				slot: "Ingredient 2",
			},
			{
				value: [
					"Broccoli",
					"Potato",
					"Asparagus",
					"Red Bell Pepper",
					"Carrot",
					"Common Mushroom",
					"Pumpkin",
				],
				slot: "Ingredient 3",
			},
		],
		baseValue: { value: 1325, unit: "G" },
		effect: "None",
		whereToUnlock: "Nadine's Bistro",
	},
	{
		name: "Fried Rice",
		group: "Main Dishes",
		ingredients: [
			{ value: "Cooked Rice", slot: "Ingredient 1" },
			{ value: ["Egg", "Silkie Egg"], slot: "Ingredient 2" },
			{ value: "Onion", slot: "Ingredient 3" },
			{ value: "Carrot", slot: "Ingredient 4" },
		],
		baseValue: { value: 1316, unit: "G" },
		effect: "None",
		whereToUnlock: "Clara's Diner",
	},
	{
		name: "Rainbow Curry",
		group: "Main Dishes",
		ingredients: [
			{ value: "Cooked Rice", slot: "Ingredient 1" },
			{ value: "Curry Powder", slot: "Ingredient 2" },
			{ value: "Spinach", slot: "Ingredient 3" },
			{ value: "Red Bell Pepper", slot: "Ingredient 4" },
		],
		baseValue: { value: 1304, unit: "G" },
		effect: "None",
		whereToUnlock: "Mini Madeleine's",
	},
	{
		name: "Yakisoba",
		group: "Main Dishes",
		ingredients: [
			{ value: "Wheat Flour", slot: "Ingredient 1" },
			{ value: "Mushrom (any)", slot: "Ingredient 2" },
			{ value: "Cabbage", slot: "Ingredient 3" },
		],
		baseValue: { value: 1271, unit: "G" },
		effect: "None",
		whereToUnlock: "Clara's Diner",
	},
	{
		name: "Unadon",
		group: "Main Dishes",
		ingredients: [
			{ value: "Cooked Rice", slot: "Ingredient 1" },
			{ value: ["Eel", "Marbled Eel"], slot: "Ingredient 2" },
			{ value: "Soy Sauce", slot: "Ingredient 3" },
			{ value: "Sugar", slot: "Ingredient 4" },
		],
		baseValue: { value: 1262, unit: "G" },
		effect: "None",
		whereToUnlock: "Clara's Diner",
	},
	{
		name: "Fried Matsutake Mushrooms",
		group: "Main Dishes",
		ingredients: [{ value: "Matsutake Mushroom", slot: "Ingredient 1" }],
		baseValue: { value: 1200, unit: "G" },
		effect: "None",
		whereToUnlock: "Felix’s Fixings (Autumn)",
	},
	{
		name: "Rice Gratin",
		group: "Main Dishes",
		ingredients: [
			{ value: "Rice", slot: "Ingredient 1" },
			{ value: "Cheese (any)", slot: "Ingredient 2" },
			{ value: "Buffalo Milk", slot: "Ingredient 3" },
		],
		baseValue: { value: 1188, unit: "G" },
		effect: "None",
		whereToUnlock: "Mini Madeleine's",
	},
	{
		name: "Herb Bread",
		group: "Main Dishes",
		ingredients: [
			{ value: "Wheat Flour", slot: "Ingredient 1" },
			{ value: "Herb Butter", slot: "Ingredient 2" },
		],
		baseValue: { value: 1182, unit: "G" },
		effect: "None",
		whereToUnlock: "Mini Madeleine's",
	},
	{
		name: "Okonomiyaki",
		group: "Main Dishes",
		ingredients: [
			{ value: "Wheat Flour", slot: "Ingredient 1" },
			{ value: "Cabbage", slot: "Ingredient 2" },
			{ value: ["Egg", "Silkie Egg"], slot: "Ingredient 3" },
		],
		baseValue: { value: 1172, unit: "G" },
		effect: "None",
		whereToUnlock: "Clara's Diner",
	},
	{
		name: "Tempura",
		group: "Main Dishes",
		ingredients: [
			{ value: "Wheat Flour", slot: "Ingredient 1" },
			{
				value: ["Oil", "Nut Oil", "Herb Oil", "Olive Oil", "Grape Oil"],
				slot: "Ingredient 2",
			},
			{ value: ["Egg", "Silkie Egg"], slot: "Ingredient 3" },
			{
				value: [
					"Shiitake Mushroom",
					"Pumpkin",
					"Eggplant",
					"Sweet Potato",
					"Icefish",
					"Pond Smelt",
				],
				slot: "Ingredient 4",
			},
		],
		baseValue: { value: 1152, unit: "G" },
		effect: "None",
		whereToUnlock: "Clara's Diner",
	},
	{
		name: "Paella",
		group: "Main Dishes",
		ingredients: [
			{ value: "Cooked Rice", slot: "Ingredient 1" },
			{
				value: [
					"Grayling",
					"Bighead Carp",
					"Nile Perch",
					"Barbel Steed",
					"Three-Lips Carp",
					"Brown Trout",
					"Black Bass",
					"Mugitsuku",
				],
				slot: "Ingredient 2",
			},
			{ value: "Red Bell Pepper", slot: "Ingredient 3" },
			{ value: "Spice", slot: "Ingredient 4" },
		],
		baseValue: { value: 1151, unit: "G" },
		effect: "None",
		whereToUnlock: "Mini Madeleine's",
	},
	{
		name: "Boiled Tofu",
		group: "Main Dishes",
		ingredients: [
			{ value: "Tofu", slot: "Ingredient 1" },
			{ value: "Napa Cabbage", slot: "Ingredient 2" },
			{ value: "Mushroom (any)", slot: "Ingredient 3" },
		],
		baseValue: { value: 1147, unit: "G" },
		effect: "None",
		usedForFestival: "Hearth Day",
		whereToUnlock: "High Quality's the Way to Go! request from Derek",
	},
	{
		name: "Pizza",
		group: "Main Dishes",
		ingredients: [
			{ value: "Wheat Flour", slot: "Ingredient 1" },
			{ value: "Tomato", slot: "Ingredient 2" },
			{ value: "Cheese (any)", slot: "Ingredient 3" },
		],
		baseValue: { value: 1142, unit: "G" },
		effect: "None",
		whereToUnlock: "Face of Zephyr Town title, Nadine's Bistro",
	},
	{
		name: "Bok Choy Soy Cream Stew",
		group: "Main Dishes",
		ingredients: [
			{ value: "Bok Choy", slot: "Ingredient 1" },
			{ value: "Soy Milk", slot: "Ingredient 2" },
			{ value: "Butter (any)", slot: "Ingredient 3" },
		],
		baseValue: { value: 1131, unit: "G" },
		effect: "None",
		usedForFestival: "Hearth Day",
		whereToUnlock: "Nadine's Bistro",
	},
	{
		name: "Curry Bread",
		group: "Main Dishes",
		ingredients: [
			{ value: "Wheat Flour", slot: "Ingredient 1" },
			{ value: "Curry Powder", slot: "Ingredient 2" },
			{
				value: ["Oil", "Nut Oil", "Herb Oil", "Olive Oil", "Grape Oil"],
				slot: "Ingredient 3",
			},
		],
		baseValue: { value: 1073, unit: "G" },
		effect: "None",
		whereToUnlock: "Nadine's Bistro",
	},
	{
		name: "Meuniére Fish",
		group: "Main Dishes",
		ingredients: [
			{
				value: [
					"Grayling",
					"Bighead Carp",
					"Nile Perch",
					"Barbel Steed",
					"Three-Lips Carp",
					"Brown Trout",
					"Black Bass",
					"Mugitsuku",
				],
				slot: "Ingredient 1",
			},
			{ value: "Wheat Flour", slot: "Ingredient 2" },
			{
				value: ["Oil", "Nut Oil", "Herb Oil", "Olive Oil", "Grape Oil"],
				slot: "Ingredient 3",
			},
		],
		baseValue: { value: 1073, unit: "G" },
		effect: "None",
		whereToUnlock: "Mini Madeleine's",
	},
	{
		name: "Rice & Mixed Vegetables",
		group: "Main Dishes",
		ingredients: [
			{ value: "Rice", slot: "Ingredient 1" },
			{ value: "Fried Tofu", slot: "Ingredient 2" },
			{ value: "Carrot", slot: "Ingredient 3" },
		],
		baseValue: { value: 1052, unit: "G" },
		effect: "None",
		whereToUnlock: "Clara's Diner",
	},
	{
		name: "Pink Fondue",
		group: "Main Dishes",
		ingredients: [
			{ value: "Grape Juice", slot: "Ingredient 1" },
			{
				value: ["Bread", "Baguettes", "White Bread", "Focaccia Bread"],
				slot: "Ingredient 2",
			},
			{
				value: [
					"Broccoli",
					"Potato",
					"Asparagus",
					"Red Bell Pepper",
					"Carrot",
					"Common Mushroom",
					"Pumpkin",
				],
				slot: "Ingredient 3",
			},
		],
		baseValue: { value: 937, unit: "G" },
		effect: "None",
		whereToUnlock: "Nadine's Bistro",
	},
	{
		name: "Curry Rice",
		group: "Main Dishes",
		ingredients: [
			{ value: "Cooked Rice", slot: "Ingredient 1" },
			{ value: "Curry Powder", slot: "Ingredient 2" },
			{ value: ["Potato", "Carrot", "Onion"], slot: "Ingredient 3" },
		],
		baseValue: { value: 911, unit: "G" },
		effect: "None",
		whereToUnlock: "Clara's Diner, Flex it out! mail from Felix",
	},
	{
		name: "Vegetable Curry",
		group: "Main Dishes",
		ingredients: [
			{ value: "Cooked Rice", slot: "Ingredient 1" },
			{ value: "Curry Powder", slot: "Ingredient 2" },
			{
				value: [
					"Cucumber",
					"Onion",
					"Asparagus",
					"Tomato",
					"Red Bell Pepper",
					"Carrot",
					"Turnip",
					"Sweet Potato",
					"Pumpkin",
					"Eggplant",
				],
				slot: "Ingredient 3",
			},
		],
		baseValue: { value: 911, unit: "G" },
		effect: "None",
		whereToUnlock: "First-Class Curry request from Diana",
	},
	{
		name: "Mushroom Rice",
		group: "Main Dishes",
		ingredients: [
			{ value: "Rice", slot: "Ingredient 1" },
			{ value: "Mushroom (any)", slot: "Ingredient 2" },
			{ value: "Mushroom (any)", slot: "Ingredient 3" },
			{ value: "Mushroom (any)", slot: "Ingredient 4" },
		],
		baseValue: { value: 874, unit: "G" },
		effect: "None",
		whereToUnlock: "Sharpen Those Skills request from Madeleine",
	},
	{
		name: "Chirashi Sushi",
		group: "Main Dishes",
		ingredients: [
			{ value: "Sashimi", slot: "Ingredient 1" },
			{ value: "Cooked Rice", slot: "Ingredient 2" },
			{ value: "Vinegar", slot: "Ingredient 3" },
			{ value: ["Egg", "Silkie Egg"], slot: "Ingredient 4" },
		],
		baseValue: { value: 867, unit: "G" },
		effect: "None",
		whereToUnlock: "Clara's Diner",
	},
	{
		name: "Zaru Soba",
		group: "Main Dishes",
		ingredients: [
			{ value: "Buckwheat Flour", slot: "Ingredient 1" },
			{ value: "Wheat Flour", slot: "Ingredient 2" },
		],
		baseValue: { value: 838, unit: "G" },
		effect: "None",
		whereToUnlock: "Clara's Diner",
	},
	{
		name: "Dry Curry",
		group: "Main Dishes",
		ingredients: [
			{ value: "Cooked Rice", slot: "Ingredient 1" },
			{ value: "Curry Powder", slot: "Ingredient 2" },
			{ value: "Tomato", slot: "Ingredient 3" },
			{ value: "Soybean", slot: "Ingredient 4" },
		],
		baseValue: { value: 837, unit: "G" },
		effect: "None",
		whereToUnlock: "Fine Dining request from Erik",
	},
	{
		name: "Bouillabaisse",
		group: "Main Dishes",
		ingredients: [
			{ value: "Tomato", slot: "Ingredient 1" },
			{
				value: [
					"Grayling",
					"Bighead Carp",
					"Nile Perch",
					"Barbel Steed",
					"Three-Lips Carp",
					"Brown Trout",
					"Black Bass",
					"Mugitsuku",
				],
				slot: "Ingredient 2",
			},
			{
				value: ["Oil", "Nut Oil", "Herb Oil", "Olive Oil", "Grape Oil"],
				slot: "Ingredient 3",
			},
		],
		baseValue: { value: 835, unit: "G" },
		effect: "None",
		usedForFestival: "Hearth Day",
		whereToUnlock: "Mini Madeleine's",
	},
	{
		name: "Steamed Mushrooms",
		group: "Main Dishes",
		ingredients: [
			{ value: "Mushroom (any)", slot: "Ingredient 1" },
			{ value: "Butter (any)", slot: "Ingredient 2" },
		],
		baseValue: { value: 809, unit: "G" },
		effect: "None",
		whereToUnlock: "Heartening Mushrooms request from Clara",
	},
	{
		name: "Tofu Steak",
		group: "Main Dishes",
		ingredients: [
			{ value: "Tofu", slot: "Ingredient 1" },
			{ value: ["Wheat Flour", "Rice Flour"], slot: "Ingredient 2" },
			{
				value: ["Oil", "Nut Oil", "Herb Oil", "Olive Oil", "Grape Oil"],
				slot: "Ingredient 3",
			},
		],
		baseValue: { value: 809, unit: "G" },
		effect: "None",
		whereToUnlock: "Mini Madeleine's",
	},
	{
		name: "Milk Rice Porridge",
		group: "Main Dishes",
		ingredients: [
			{ value: "Rice", slot: "Ingredient 1" },
			{ value: "Salt", slot: "Ingredient 2" },
			{ value: ["Milk", "Buffalo Milk"], slot: "Ingredient 3" },
		],
		baseValue: { value: 801, unit: "G" },
		effect: "None",
		whereToUnlock: "Mini Madeleine's",
	},
	{
		name: "Fried Onigiri",
		group: "Main Dishes",
		ingredients: [
			{ value: "Onigiri", slot: "Ingredient 1" },
			{ value: "Soy Sauce", slot: "Ingredient 2" },
		],
		baseValue: { value: 735, unit: "G" },
		effect: "None",
		whereToUnlock: "Mini Madeleine's",
	},
	{
		name: "Omelet",
		group: "Main Dishes",
		ingredients: [
			{ value: ["Egg", "Silkie Egg"], slot: "Ingredient 1" },
			{ value: "Butter (any)", slot: "Ingredient 2" },
		],
		baseValue: { value: 721, unit: "G" },
		effect: "None",
		whereToUnlock: "Café Madeleine",
	},
	{
		name: "Donburi Rice Bowl",
		group: "Main Dishes",
		ingredients: [
			{ value: ["Egg", "Silkie Egg"], slot: "Ingredient 1" },
			{ value: "Onion", slot: "Ingredient 2" },
			{ value: "Cooked Rice", slot: "Ingredient 3" },
		],
		baseValue: { value: 664, unit: "G" },
		effect: "None",
		whereToUnlock: "Clara's Diner",
	},
	{
		name: "Sushi",
		group: "Main Dishes",
		ingredients: [
			{ value: "Sashimi", slot: "Ingredient 1" },
			{ value: "Cooked Rice", slot: "Ingredient 2" },
			{ value: "Vinegar", slot: "Ingredient 3" },
		],
		baseValue: { value: 657, unit: "G" },
		effect: "None",
		whereToUnlock: "Let's get cooking! mail, Clara's Diner",
	},
	{
		name: "Tomato Fondue",
		group: "Main Dishes",
		ingredients: [
			{ value: "Tomato", slot: "Ingredient 1" },
			{
				value: ["Bread", "White Bread", "Baguettes", "Focaccia Bread"],
				slot: "Ingredient 2",
			},
			{
				value: [
					"Broccoli",
					"Potato",
					"Asparagus",
					"Red Bell Pepper",
					"Carrot",
					"Common Mushroom",
					"Pumpkin",
				],
				slot: "Ingredient 3",
			},
		],
		baseValue: { value: 650, unit: "G" },
		effect: "None",
		whereToUnlock: "Nadine's Bistro",
	},
	{
		name: "Fruit Sandwich",
		group: "Main Dishes",
		ingredients: [
			{
				value: ["Bread", "White Bread", "Baguettes", "Focaccia Bread"],
				slot: "Ingredient 1",
			},
			{
				value: [
					"Cherry",
					"Blueberry",
					"Green Grapes",
					"Strawberry",
					"Mango",
					"Pineapple",
					"Banana",
					"Peach",
					"Orange",
					"Melon",
				],
				slot: "Ingredient 2",
			},
			{
				value: [
					"Cherry",
					"Blueberry",
					"Green Grapes",
					"Strawberry",
					"Mango",
					"Pineapple",
					"Banana",
					"Peach",
					"Orange",
					"Melon",
				],
				slot: "Ingredient 3",
			},
		],
		baseValue: { value: 647, unit: "G" },
		effect: "None",
		whereToUnlock: "Mini Madeleine's",
	},
	{
		name: "Herb Rice Porridge",
		group: "Main Dishes",
		ingredients: [
			{ value: "Rice", slot: "Ingredient 1" },
			{ value: "Salt", slot: "Ingredient 2" },
			{ value: ["Mint", "Chamomile", "Lavender"], slot: "Ingredient 3" },
		],
		baseValue: { value: 647, unit: "G" },
		effect: "None",
		whereToUnlock: "Some Herbs, Please? request from Sophie",
	},
	{
		name: "Udon",
		group: "Main Dishes",
		ingredients: [
			{ value: "Wheat Flour", slot: "Ingredient 1" },
			{ value: "Fish Cake", slot: "Ingredient 2" },
			{ value: "Green Onion", slot: "Ingredient 3" },
		],
		baseValue: { value: 647, unit: "G" },
		effect: "None",
		usedForFestival: "Hearth Day",
		whereToUnlock: "Clara's Diner",
	},
	{
		name: "Herb Pasta",
		group: "Main Dishes",
		ingredients: [
			{ value: "Wheat Flour", slot: "Ingredient 1" },
			{ value: ["Mint", "Chamomile", "Lavender"], slot: "Ingredient 2" },
			{
				value: ["Oil", "Nut Oil", "Herb Oil", "Olive Oil", "Grape Oil"],
				slot: "Ingredient 3",
			},
		],
		baseValue: { value: 616, unit: "G" },
		effect: "None",
		whereToUnlock: "Bookshelves in Jules' and Derek's House",
	},
	{
		name: "Penne Pasta",
		group: "Main Dishes",
		ingredients: [
			{ value: "Wheat Flour", slot: "Ingredient 1" },
			{
				value: ["Oil", "Nut Oil", "Herb Oil", "Olive Oil", "Grape Oil"],
				slot: "Ingredient 2",
			},
			{ value: "Tomato", slot: "Ingredient 3" },
		],
		baseValue: { value: 604, unit: "G" },
		effect: "None",
		whereToUnlock: "Nadine's Bistro",
	},
	{
		name: "Rice Porridge",
		group: "Main Dishes",
		ingredients: [
			{ value: "Rice", slot: "Ingredient 1" },
			{ value: "Salt", slot: "Ingredient 2" },
		],
		baseValue: { value: 544, unit: "G" },
		effect: "None",
		whereToUnlock: "Café Madeleine",
	},
	{
		name: "Simmered Fish",
		group: "Main Dishes",
		ingredients: [
			{
				value: [
					"Bluegill",
					"Willow Shiner",
					"Killifish",
					"Stone Moroko",
					"Pond Smelt",
					"Sweetfish",
					"Eel",
					"Marbled Eel",
					"Goldfish",
					"Crucian Carp",
				],
				slot: "Ingredient 1",
			},
			{ value: "Soy Sauce", slot: "Ingredient 2" },
		],
		baseValue: { value: 451, unit: "G" },
		effect: "None",
		whereToUnlock: "Clara's Diner",
	},
	{
		name: "Raisin Bread",
		group: "Main Dishes",
		ingredients: [
			{ value: "Wheat Flour", slot: "Ingredient 1" },
			{ value: "Red Grapes", slot: "Ingredient 2" },
		],
		baseValue: { value: 444, unit: "G" },
		effect: "None",
		whereToUnlock: "Clara's Diner",
	},
	{
		name: "Sandwich",
		group: "Main Dishes",
		ingredients: [
			{
				value: ["Bread", "White Bread", "Baguettes", "Focaccia Bread"],
				slot: "Ingredient 1",
			},
			{ value: "Tomato", slot: "Ingredient 2" },
			{ value: "Cucumber", slot: "Ingredient 3" },
		],
		baseValue: { value: 375, unit: "G" },
		effect: "None",
		whereToUnlock: "Café Madeleine",
	},
	{
		name: "Onigiri",
		group: "Main Dishes",
		ingredients: [
			{ value: "Cooked Rice", slot: "Ingredient 1" },
			{ value: "Seaweed", slot: "Ingredient 2" },
		],
		baseValue: { value: 370, unit: "G" },
		effect: "None",
		whereToUnlock: "Café Madeleine",
	},
	{
		name: "Fried Eggplant",
		group: "Main Dishes",
		ingredients: [
			{ value: "Eggplant", slot: "Ingredient 1" },
			{
				value: ["Oil", "Nut Oil", "Herb Oil", "Olive Oil", "Grape Oil"],
				slot: "Ingredient 2",
			},
		],
		baseValue: { value: 342, unit: "G" },
		effect: "None",
		whereToUnlock: "Felix’s Fixings (except Winter)",
	},
	{
		name: "Chestnut Rice",
		group: "Main Dishes",
		ingredients: [
			{ value: "Cooked Rice", slot: "Ingredient 1" },
			{ value: "Chestnut", slot: "Ingredient 2" },
		],
		baseValue: { value: 329, unit: "G" },
		effect: "None",
		whereToUnlock: "Clara's Diner",
	},
	{
		name: "Pasta",
		group: "Main Dishes",
		ingredients: [
			{ value: "Wheat Flour", slot: "Ingredient 1" },
			{ value: ["Egg", "Silkie Egg"], slot: "Ingredient 2" },
		],
		baseValue: { value: 328, unit: "G" },
		effect: "None",
		whereToUnlock: "Café Madeleine",
	},
	{
		name: "Herb Sandwich",
		group: "Main Dishes",
		ingredients: [
			{
				value: ["Bread", "White Bread", "Baguettes", "Focaccia Bread"],
				slot: "Ingredient 1",
			},
			{ value: ["Mint", "Chamomile", "Lavender"], slot: "Ingredient 2" },
			{ value: "Mayonnaise (any)", slot: "Ingredient 3" },
		],
		baseValue: { value: 817, unit: "G" },
		effect: "None",
		whereToUnlock: "Secret Ingredient request from Mina",
	},
	{
		name: "Egg Over Rice",
		group: "Main Dishes",
		ingredients: [
			{ value: ["Egg", "Silkie Egg"], slot: "Ingredient 1" },
			{ value: "Cooked Rice", slot: "Ingredient 2" },
		],
		baseValue: { value: 248, unit: "G" },
		effect: "None",
		whereToUnlock: "Available at the start",
	},
	{
		name: "Grilled Fish",
		group: "Main Dishes",
		ingredients: [
			{
				value: [
					"Amur Minnow",
					"Dace",
					"Pale Chub",
					"Sculpin",
					"Dark Chub",
					"Bitterling",
					"Tamoroko",
					"Rainbow Trout",
					"Silver Carp",
					"Basa",
				],
				slot: "Ingredient 1",
			},
		],
		baseValue: { value: 195, unit: "G" },
		effect: "None",
		whereToUnlock: "Available at the start",
	},
	{
		name: "Rüeblitorte",
		group: "Desserts",
		ingredients: [
			{ value: "Wheat Flour", slot: "Ingredient 1" },
			{ value: "Silkie Egg", slot: "Ingredient 2" },
			{ value: "Three-Forked Carrot", slot: "Ingredient 3" },
			{ value: "Lemon", slot: "Ingredient 4" },
		],
		baseValue: { value: 2506, unit: "G" },
		effect: "Jump Distance Up",
		usedForFestival: "Hearth Day",
		whereToUnlock: "It's Gotta Be PERFECT! request from Sylvia",
	},
	{
		name: "Trifle",
		group: "Desserts",
		ingredients: [
			{ value: "Castella", slot: "Ingredient 1" },
			{ value: "Silkie Egg+", slot: "Ingredient 2" },
			{ value: "Yogurt+", slot: "Ingredient 3" },
			{
				value: [
					"Cherry",
					"Blueberry",
					"Green Grapes",
					"Strawberry",
					"Mango",
					"Pineapple",
					"Banana",
					"Peach",
					"Orange",
					"Melon",
				],
				slot: "Ingredient 4",
			},
		],
		baseValue: { value: 6192, unit: "G" },
		effect: "Petting Happiness Up Lv. 4",
		usedForFestival: "Pumpkin Festival",
		whereToUnlock: "The Gift of Gratitude request from Samir",
	},
	{
		name: "Pineapple Pie",
		group: "Desserts",
		ingredients: [
			{ value: "Wheat Flour", slot: "Ingredient 1" },
			{ value: ["Egg", "Silkie Egg"], slot: "Ingredient 2" },
			{ value: "Butter (any)", slot: "Ingredient 3" },
			{ value: "Jewel Pineapple", slot: "Ingredient 4" },
		],
		baseValue: { value: 3130, unit: "G" },
		effect: "Petting Happiness Up Lv. 4",
		usedForFestival: "Pumpkin Festival",
		whereToUnlock:
			"Reward for giving high quality tea for the Tea Party Festival",
	},
	{
		name: "Cheesecake",
		group: "Desserts",
		ingredients: [
			{ value: "Wheat Flour", slot: "Ingredient 1" },
			{ value: ["Egg", "Silkie Egg"], slot: "Ingredient 2" },
			{ value: "Buffalo Milk", slot: "Ingredient 3" },
			{ value: "Cheese (any)", slot: "Ingredient 4" },
		],
		baseValue: { value: 1602, unit: "G" },
		effect: "Petting Happiness Up Lv. 3",
		usedForFestival: "Pumpkin Festival",
		whereToUnlock: "Dairy Driver title, Nadine's Bistro",
	},
	{
		name: "Steamed Cake",
		group: "Desserts",
		ingredients: [
			{ value: "Wheat Flour", slot: "Ingredient 1" },
			{ value: ["Egg", "Silkie Egg"], slot: "Ingredient 2" },
			{ value: ["Milk", "Buffalo Milk"], slot: "Ingredient 3" },
			{ value: "Pumpkin", slot: "Ingredient 4" },
		],
		baseValue: { value: 1422, unit: "G" },
		effect: "Petting Happiness Up Lv. 3",
		usedForFestival: "Pumpkin Festival",
		whereToUnlock: "Mini Madeleine's",
	},
	{
		name: "Cherry Pie",
		group: "Desserts",
		ingredients: [
			{ value: "Wheat Flour", slot: "Ingredient 1" },
			{ value: ["Egg", "Silkie Egg"], slot: "Ingredient 2" },
			{ value: "Butter (any)", slot: "Ingredient 3" },
			{ value: "Cherry", slot: "Ingredient 4" },
		],
		baseValue: { value: 1404, unit: "G" },
		effect: "Petting Happiness Up Lv. 3",
		usedForFestival: "Pumpkin Festival",
		whereToUnlock: "Making Something Special! request from Maple",
	},
	{
		name: "Blueberry Pie",
		group: "Desserts",
		ingredients: [
			{ value: "Wheat Flour", slot: "Ingredient 1" },
			{ value: ["Egg", "Silkie Egg"], slot: "Ingredient 2" },
			{ value: "Butter (any)", slot: "Ingredient 3" },
			{ value: "Blueberry", slot: "Ingredient 4" },
		],
		baseValue: { value: 1377, unit: "G" },
		effect: "Petting Happiness Up Lv. 3",
		usedForFestival: "Pumpkin Festival",
		whereToUnlock: "Nadine's Bistro",
	},
	{
		name: "Strawberry Pie",
		group: "Desserts",
		ingredients: [
			{ value: "Wheat Flour", slot: "Ingredient 1" },
			{ value: ["Egg", "Silkie Egg"], slot: "Ingredient 2" },
			{ value: "Butter (any)", slot: "Ingredient 3" },
			{ value: "Strawberry", slot: "Ingredient 4" },
		],
		baseValue: { value: 1368, unit: "G" },
		effect: "Petting Happiness Up Lv. 3",
		usedForFestival: "Pumpkin Festival",
		whereToUnlock: "Acrobat title, Café Madeleine",
	},
	{
		name: "Donuts",
		group: "Desserts",
		ingredients: [
			{ value: "Wheat Flour", slot: "Ingredient 1" },
			{ value: ["Egg", "Silkie Egg"], slot: "Ingredient 2" },
			{ value: "Sugar", slot: "Ingredient 3" },
			{
				value: ["Oil", "Nut Oil", "Herb Oil", "Olive Oil", "Grape Oil"],
				slot: "Ingredient 4",
			},
		],
		baseValue: { value: 1332, unit: "G" },
		effect: "Petting Happiness Up Lv. 3",
		usedForFestival: "Pumpkin Festival",
		whereToUnlock:
			"Excellent Eggs request from Sylvia, Me and mom baked em! mail from Sylvia",
	},
	{
		name: "Churros",
		group: "Desserts",
		ingredients: [
			{ value: "Wheat Flour", slot: "Ingredient 1" },
			{ value: ["Egg", "Silkie Egg"], slot: "Ingredient 2" },
			{
				value: ["Oil", "Nut Oil", "Herb Oil", "Olive Oil", "Grape Oil"],
				slot: "Ingredient 3",
			},
			{ value: "Sugar", slot: "Ingredient 4" },
		],
		baseValue: { value: 1332, unit: "G" },
		effect: "Petting Happiness Up Lv. 3",
		usedForFestival: "Pumpkin Festival",
		whereToUnlock:
			"Scene Stealer title, Mini Madeleine's, A rare treat! mail from Maple",
	},
	{
		name: "Chocolate Cake",
		group: "Desserts",
		ingredients: [
			{ value: "Wheat Flour", slot: "Ingredient 1" },
			{ value: ["Egg", "Silkie Egg"], slot: "Ingredient 2" },
			{ value: ["Milk", "Buffalo Milk"], slot: "Ingredient 3" },
			{ value: "Chocolate", slot: "Ingredient 4" },
		],
		baseValue: { value: 1242, unit: "G" },
		effect: "Petting Happiness Up Lv. 3",
		usedForFestival: "Pumpkin Festival",
		whereToUnlock: "Clara's Diner",
	},
	{
		name: "Baumkuchen",
		group: "Desserts",
		ingredients: [
			{ value: "Wheat Flour", slot: "Ingredient 1" },
			{ value: ["Egg", "Silkie Egg"], slot: "Ingredient 2" },
			{ value: ["Milk", "Buffalo Milk"], slot: "Ingredient 3" },
			{ value: "Sugar", slot: "Ingredient 4" },
		],
		baseValue: { value: 1242, unit: "G" },
		effect: "Petting Happiness Up Lv. 3",
		usedForFestival: "Pumpkin Festival",
		whereToUnlock: "It's Gotta Be Yummy request from Laurie",
	},
	{
		name: "Engadiner Nusstorte",
		group: "Desserts",
		ingredients: [
			{ value: "Wheat Flour", slot: "Ingredient 1" },
			{ value: "Silkie Egg", slot: "Ingredient 2" },
			{ value: "Sugar", slot: "Ingredient 3" },
			{ value: "Walnut", slot: "Ingredient 4" },
		],
		baseValue: { value: 1206, unit: "G" },
		effect: "Petting Happiness Up Lv. 3",
		usedForFestival: "Hearth Day",
		whereToUnlock: "Nadine's Bistro",
	},
	{
		name: "Pancakes",
		group: "Desserts",
		ingredients: [
			{ value: "Wheat Flour", slot: "Ingredient 1" },
			{ value: ["Egg", "Silkie Egg"], slot: "Ingredient 2" },
			{ value: ["Milk", "Buffalo Milk"], slot: "Ingredient 3" },
			{ value: "Honey (any)", slot: "Ingredient 4" },
		],
		baseValue: { value: 1152, unit: "G" },
		effect: "Petting Happiness Up Lv. 3",
		usedForFestival: "Pumpkin Festival",
		whereToUnlock: "Café Madeleine",
	},
	{
		name: "Fruit Dumplings",
		group: "Desserts",
		ingredients: [
			{ value: "Refined Rice Flour", slot: "Ingredient 1" },
			{
				value: [
					"Cherry",
					"Blueberry",
					"Green Grapes",
					"Strawberry",
					"Mango",
					"Pineapple",
					"Banana",
					"Peach",
					"Orange",
					"Melon",
				],
				slot: "Ingredient 2",
			},
			{
				value: [
					"Cherry",
					"Blueberry",
					"Green Grapes",
					"Strawberry",
					"Mango",
					"Pineapple",
					"Banana",
					"Peach",
					"Orange",
					"Melon",
				],
				slot: "Ingredient 3",
			},
		],
		baseValue: { value: 1089, unit: "G" },
		effect: "Petting Happiness Up Lv. 3",
		usedForFestival: "Pumpkin Festival",
		whereToUnlock: "Mini Madeleine's",
	},
	{
		name: "Sweet Potato Cakes",
		group: "Desserts",
		ingredients: [
			{ value: ["Milk", "Buffalo Milk"], slot: "Ingredient 1" },
			{ value: "Sugar", slot: "Ingredient 2" },
			{ value: "Sweet Potato", slot: "Ingredient 3" },
		],
		baseValue: { value: 932, unit: "G" },
		effect: "Petting Happiness Up Lv. 2",
		usedForFestival: "Pumpkin Festival",
		whereToUnlock: "Nadine's Bistro",
	},
	{
		name: "Chocolate Fondue",
		group: "Desserts",
		ingredients: [
			{ value: "Chocolate", slot: "Ingredient 1" },
			{
				value: ["Bread", "White Bread", "Baguettes", "Focaccia Bread"],
				slot: "Ingredient 2",
			},
			{
				value: [
					"Apple",
					"Red Grapes",
					"Green Grapes",
					"Strawberry",
					"Mango",
					"Pineapple",
					"Banana",
					"Peach",
					"Orange",
					"Melon",
				],
				slot: "Ingredient 3",
			},
		],
		baseValue: { value: 924, unit: "G" },
		effect: "Petting Happiness Up Lv. 2",
		usedForFestival: "Pumpkin Festival",
		whereToUnlock: "Nadine's Bistro",
	},
	{
		name: "Baked Apple",
		group: "Desserts",
		ingredients: [
			{ value: "Apple", slot: "Ingredient 1" },
			{ value: "Butter (any)", slot: "Ingredient 2" },
		],
		baseValue: { value: 838, unit: "G" },
		effect: "Petting Happiness Up Lv. 2",
		usedForFestival: "Pumpkin Festival",
		whereToUnlock: "Felix’s Fixings (Autumn)",
	},
	{
		name: "Ice Cream",
		group: "Desserts",
		ingredients: [
			{ value: ["Milk", "Buffalo Milk"], slot: "Ingredient 1" },
			{ value: ["Egg", "Silkie Egg"], slot: "Ingredient 2" },
			{ value: "Sugar", slot: "Ingredient 3" },
		],
		baseValue: { value: 832, unit: "G" },
		effect: "Petting Happiness Up Lv. 2",
		usedForFestival: "Pumpkin Festival",
		whereToUnlock: "Bookshelves in June's House",
	},
	{
		name: "Castella",
		group: "Desserts",
		ingredients: [
			{ value: "Wheat Flour", slot: "Ingredient 1" },
			{ value: "Silkie Egg", slot: "Ingredient 2" },
			{ value: "Honey (any)", slot: "Ingredient 3" },
		],
		baseValue: { value: 801, unit: "G" },
		effect: "Petting Happiness Up Lv. 2",
		usedForFestival: "Pumpkin Festival",
		whereToUnlock: "Clara's Diner",
	},
	{
		name: "Strawberry Mochi",
		group: "Desserts",
		ingredients: [
			{ value: "Mochi", slot: "Ingredient 1" },
			{ value: "Strawberry", slot: "Ingredient 2" },
		],
		baseValue: { value: 618, unit: "G" },
		effect: "Petting Happiness Up Lv. 2",
		usedForFestival: "Pumpkin Festival",
		whereToUnlock:
			"Big Hops title, Clara's Diner, Hip ideas of the youth mail from Madeleine",
	},
	{
		name: "Egg Tart",
		group: "Desserts",
		ingredients: [
			{ value: ["Egg", "Silkie Egg"], slot: "Ingredient 1" },
			{ value: ["Milk", "Buffalo Milk"], slot: "Ingredient 2" },
			{ value: "Wheat Flour", slot: "Ingredient 3" },
		],
		baseValue: { value: 601, unit: "G" },
		effect: "Petting Happiness Up Lv. 2",
		usedForFestival: "Pumpkin Festival",
		whereToUnlock: "Milker title",
	},
	{
		name: "Cake",
		group: "Desserts",
		ingredients: [
			{ value: "Wheat Flour", slot: "Ingredient 1" },
			{ value: ["Egg", "Silkie Egg"], slot: "Ingredient 2" },
			{ value: ["Milk", "Buffalo Milk"], slot: "Ingredient 3" },
		],
		baseValue: { value: 601, unit: "G" },
		effect: "Petting Happiness Up Lv. 2",
		usedForFestival: "Pumpkin Festival",
		whereToUnlock:
			"Cheer Captain title, Nadine's Bistro, Everything changes! mail from Gabriel",
	},
	{
		name: "Dango",
		group: "Desserts",
		ingredients: [{ value: "Refined Rice Flour", slot: "Ingredient 1" }],
		baseValue: { value: 588, unit: "G" },
		effect: "Petting Happiness Up Lv. 2",
		usedForFestival: "Pumpkin Festival",
		whereToUnlock: "Café Madeleine",
	},
	{
		name: "Wrapped Rice Cakes",
		group: "Desserts",
		ingredients: [
			{ value: "Mochi", slot: "Ingredient 1" },
			{ value: "Summer Tea Leaves", slot: "Ingredient 2" },
		],
		baseValue: { value: 544, unit: "G" },
		effect: "Petting Happiness Up Lv. 2",
		usedForFestival: "Pumpkin Festival",
		whereToUnlock: "Clara's Diner",
	},
	{
		name: "Walnut Cookies",
		group: "Desserts",
		ingredients: [
			{ value: "Wheat Flour", slot: "Ingredient 1" },
			{ value: ["Egg", "Silkie Egg"], slot: "Ingredient 2" },
			{ value: "Walnut", slot: "Ingredient 3" },
		],
		baseValue: { value: 524, unit: "G" },
		effect: "Petting Happiness Up Lv. 2",
		usedForFestival: "Pumpkin Festival",
		whereToUnlock: "Ivy's Friend title, Café Madeleine",
	},
	{
		name: "Soy Milk Pudding",
		group: "Desserts",
		ingredients: [
			{ value: ["Milk", "Buffalo Milk"], slot: "Ingredient 1" },
			{ value: ["Egg", "Silkie Egg"], slot: "Ingredient 2" },
			{ value: "Soy Milk", slot: "Ingredient 3" },
		],
		baseValue: { value: 501, unit: "G" },
		effect: "Petting Happiness Up Lv. 2",
		usedForFestival: "Pumpkin Festival",
		whereToUnlock: "Mini Madeleine's, Energies entwined mail from Kagetsu",
	},
	{
		name: "Herb Cookies",
		group: "Desserts",
		ingredients: [
			{ value: "Wheat Flour", slot: "Ingredient 1" },
			{ value: ["Egg", "Silkie Egg"], slot: "Ingredient 2" },
			{ value: ["Mint", "Chamomile", "Lavender"], slot: "Ingredient 3" },
		],
		baseValue: { value: 415, unit: "G" },
		effect: "Petting Happiness Up Lv. 1",
		usedForFestival: "Pumpkin Festival",
		whereToUnlock: "Mini Madeleine's, A kind gesture mail from Diana",
	},
	{
		name: "Toasted Mochi",
		group: "Desserts",
		ingredients: [{ value: "Mochi", slot: "Ingredient 1" }],
		baseValue: { value: 390, unit: "G" },
		effect: "Petting Happiness Up Lv. 1",
		usedForFestival: "Pumpkin Festival",
		whereToUnlock: "Mini Madeleine's",
	},
	{
		name: "Chestnut Paste",
		group: "Desserts",
		ingredients: [{ value: "Bottled Chestnuts", slot: "Ingredient 1" }],
		baseValue: { value: 390, unit: "G" },
		effect: "Petting Happiness Up Lv. 1",
		usedForFestival: "Pumpkin Festival",
		whereToUnlock: "Tempura Temptations request from Nadine",
	},
	{
		name: "Whole Cheesecake",
		group: "Desserts",
		ingredients: [
			{ value: "Wheat Flour", slot: "Ingredient 1" },
			{ value: ["Egg+", "Silkie Egg+"], slot: "Ingredient 2" },
			{ value: "Buffalo Milk+", slot: "Ingredient 3" },
			{ value: "Cheese (any)", slot: "Ingredient 4" },
		],
		baseValue: { value: 2746, unit: "G" },
		effect: "Petting Rare Item % Lv. 4",
		usedForFestival: "Pumpkin Festival",
		whereToUnlock: "Nadine's Bistro",
	},
	{
		name: "Whole Chocolate Cake",
		group: "Desserts",
		ingredients: [
			{ value: "Wheat Flour", slot: "Ingredient 1" },
			{ value: ["Egg+", "Silkie Egg+"], slot: "Ingredient 2" },
			{ value: ["Milk+", "Buffalo Milk+"], slot: "Ingredient 3" },
			{ value: "Chocolate", slot: "Ingredient 4" },
		],
		baseValue: { value: 1786, unit: "G" },
		effect: "Petting Rare Item % Lv. 4",
		usedForFestival: "Pumpkin Festival",
		whereToUnlock: "Win the Bake-Off! Festival",
	},
	{
		name: "Apple Pie",
		group: "Desserts",
		ingredients: [
			{ value: "Wheat Flour", slot: "Ingredient 1" },
			{ value: ["Egg", "Silkie Egg"], slot: "Ingredient 2" },
			{ value: "Butter (any)", slot: "Ingredient 3" },
			{ value: "Apple", slot: "Ingredient 4" },
		],
		baseValue: { value: 1458, unit: "G" },
		effect: "Petting Rare Item % Lv. 3",
		usedForFestival: "Pumpkin Festival",
		whereToUnlock: "Calm Amongst Chaos request from Clara",
	},
	{
		name: "Whole Cake",
		group: "Desserts",
		ingredients: [
			{ value: "Wheat Flour", slot: "Ingredient 1" },
			{ value: ["Egg+", "Silkie Egg+"], slot: "Ingredient 2" },
			{ value: ["Milk+", "Buffalo Milk+"], slot: "Ingredient 3" },
			{ value: "Strawberry", slot: "Ingredient 4" },
		],
		baseValue: { value: 1350, unit: "G" },
		effect: "Petting Rare Item % Lv. 3",
		usedForFestival: "Pumpkin Festival",
		whereToUnlock: "Nadine's Bistro",
	},
	{
		name: "Mont Blanc Cake",
		group: "Desserts",
		ingredients: [
			{ value: "Wheat Flour", slot: "Ingredient 1" },
			{ value: ["Egg", "Silkie Egg"], slot: "Ingredient 2" },
			{ value: ["Milk", "Buffalo Milk"], slot: "Ingredient 3" },
			{ value: "Bottled Chestnuts", slot: "Ingredient 4" },
		],
		baseValue: { value: 1242, unit: "G" },
		effect: "Petting Rare Item % Lv. 3",
		usedForFestival: "Pumpkin Festival",
		whereToUnlock: "Nadine's Bistro",
	},
	{
		name: "Pumpkin Pudding",
		group: "Desserts",
		ingredients: [
			{ value: ["Milk", "Buffalo Milk"], slot: "Ingredient 1" },
			{ value: ["Egg", "Silkie Egg"], slot: "Ingredient 2" },
			{ value: "Pumpkin", slot: "Ingredient 3" },
		],
		baseValue: { value: 986, unit: "G" },
		effect: "Petting Rare Item % Lv. 2",
		usedForFestival: "Pumpkin Festival",
		whereToUnlock: "Nadine's Bistro",
	},
	{
		name: "Chocolate Cookies",
		group: "Desserts",
		ingredients: [
			{ value: "Wheat Flour", slot: "Ingredient 1" },
			{ value: ["Egg", "Silkie Egg"], slot: "Ingredient 2" },
			{ value: "Chocolate", slot: "Ingredient 3" },
		],
		baseValue: { value: 832, unit: "G" },
		effect: "Petting Rare Item % Lv. 2",
		usedForFestival: "Pumpkin Festival",
		whereToUnlock: "Clara's Diner",
	},
	{
		name: "Honey Cake",
		group: "Desserts",
		ingredients: [
			{ value: "Wheat Flour", slot: "Ingredient 1" },
			{ value: ["Egg", "Silkie Egg"], slot: "Ingredient 2" },
			{ value: "Honey (any)", slot: "Ingredient 3" },
		],
		baseValue: { value: 755, unit: "G" },
		effect: "Petting Rare Item % Lv. 2",
		usedForFestival: "Honey Day, Pumpkin Festival",
		whereToUnlock: "First Honey Day",
	},
	{
		name: "Chocolate-Covered Banana",
		group: "Desserts",
		ingredients: [
			{ value: "Banana", slot: "Ingredient 1" },
			{ value: "Chocolate", slot: "Ingredient 2" },
		],
		baseValue: { value: 735, unit: "G" },
		effect: "Petting Rare Item % Lv. 2",
		usedForFestival: "Pumpkin Festival",
		whereToUnlock: "Café Madeleine (seasonal, dunno which season)",
	},
	{
		name: "Pudding",
		group: "Desserts",
		ingredients: [
			{ value: ["Milk", "Buffalo Milk"], slot: "Ingredient 1" },
			{ value: ["Egg", "Silkie Egg"], slot: "Ingredient 2" },
		],
		baseValue: { value: 328, unit: "G" },
		effect: "Petting Rare Item % Lv. 1",
		usedForFestival: "Pumpkin Festival",
		whereToUnlock:
			"Generous Forager title, Nadine's Bistro, Family seal of approval! mail from Felix",
	},
	{
		name: "Cookies",
		group: "Desserts",
		ingredients: [
			{ value: "Wheat Flour", slot: "Ingredient 1" },
			{ value: ["Egg", "Silkie Egg"], slot: "Ingredient 2" },
		],
		baseValue: { value: 328, unit: "G" },
		effect: "Petting Rare Item % Lv. 1",
		usedForFestival: "Pumpkin Festival",
		whereToUnlock: "Cheer Leader title, Café Madeleine",
	},
	{
		name: "Soy Milk",
		group: "Other Recipes",
		ingredients: [{ value: "Soybean", slot: "Ingredient 1" }],
		baseValue: { value: 85, unit: "G" },
		effect: "Max Stamina Up Lv. 1",
		whereToUnlock: "Café Madeleine",
	},
	{
		name: "Honey Juice",
		group: "Other Recipes",
		ingredients: [{ value: "Honey (any)", slot: "Ingredient 1" }],
		baseValue: { value: 325, unit: "G" },
		effect: "Stamina Saver Lv. 1",
		whereToUnlock: "Generous Beekeeper title, Café Madeleine",
	},
	{
		name: "Simmered Seaweed",
		group: "Other Recipes",
		ingredients: [
			{ value: "Seaweed", slot: "Ingredient 1" },
			{ value: "Soy Sauce", slot: "Ingredient 2" },
		],
		baseValue: { value: 424, unit: "G" },
		effect: "Rod Durability Up Lv. 1",
		whereToUnlock: "Clara's Diner",
	},
	{
		name: "Summer Blend Tea",
		group: "Other Recipes",
		ingredients: [{ value: "Summer Blend Tea Tin", slot: "Ingredient 1" }],
		baseValue: { value: 1287, unit: "G" },
		effect: "Run Speed Up Lv. 3",
		usedForFestival: "Hearth Day",
		whereToUnlock: "Café Madeleine (Summer Only)",
	},
	{
		name: "Summer Juice",
		group: "Other Recipes",
		ingredients: [
			{ value: "Banana Juice", slot: "Ingredient 1" },
			{ value: "Peach Juice", slot: "Ingredient 2" },
			{ value: "Lemon Juice", slot: "Ingredient 3" },
		],
		baseValue: { value: 1020, unit: "G" },
		effect: "Run Speed Up Lv. 3",
		whereToUnlock: "Mini Madeleine's (Summer Only)",
	},
	{
		name: "Black Tea",
		group: "Other Recipes",
		ingredients: [{ value: "Black Tea Tin", slot: "Ingredient 1" }],
		baseValue: { value: 401, unit: "G" },
		effect: "Watering Rare Crop % Lv. 1",
		usedForFestival: "Hearth Day",
		whereToUnlock: "Café Madeleine, A trip with a goddess mail from Erik",
	},
	{
		name: "Golden Blend Tea",
		group: "Other Recipes",
		ingredients: [{ value: "Golden Blend Tea Tin", slot: "Ingredient 1" }],
		baseValue: { value: 13031, unit: "G" },
		effect: "Chat Friendship Boost Lv. 4",
		usedForFestival: "Hearth Day",
		whereToUnlock: "Apple Pie Award request from Clara",
	},
	{
		name: "Watermelon Tea",
		group: "Other Recipes",
		ingredients: [{ value: "Watermelon Tea Tin", slot: "Ingredient 1" }],
		baseValue: { value: 2148, unit: "G" },
		effect: "Chat Friendship Boost Lv. 4",
		usedForFestival: "Hearth Day",
		whereToUnlock: "Mini Madeleine's",
	},
	{
		name: "Melon Tea",
		group: "Other Recipes",
		ingredients: [{ value: "Melon Tea Tin", slot: "Ingredient 1" }],
		baseValue: { value: 1901, unit: "G" },
		effect: "Chat Friendship Boost Lv. 4",
		usedForFestival: "Hearth Day",
		whereToUnlock: "Mini Madeleine's",
	},
	{
		name: "Jam Tea",
		group: "Other Recipes",
		ingredients: [
			{ value: "Black Tea", slot: "Ingredient 1" },
			{
				value: ["Apple Jam", "Strawberry Jam", "Grape Jam", "Blueberry Jam"],
				slot: "Ingredient 2",
			},
		],
		baseValue: { value: 1850, unit: "G" },
		effect: "Chat Friendship Boost Lv. 4",
		usedForFestival: "Hearth Day",
		whereToUnlock: "Mini Madeleine's",
	},
	{
		name: "Pineapple Tea",
		group: "Other Recipes",
		ingredients: [{ value: "Pineapple Tea Tin", slot: "Ingredient 1" }],
		baseValue: { value: 1320, unit: "G" },
		effect: "Chat Friendship Boost Lv. 3",
		usedForFestival: "Hearth Day",
		whereToUnlock: "Mini Madeleine's",
	},
	{
		name: "Spring Blend Tea",
		group: "Other Recipes",
		ingredients: [{ value: "Spring Blend Tea Tin", slot: "Ingredient 1" }],
		baseValue: { value: 1287, unit: "G" },
		effect: "Chat Friendship Boost Lv. 3",
		usedForFestival: "Hearth Day",
		whereToUnlock: "Café Madeleine (Spring Only)",
	},
	{
		name: "Royal Milk Tea",
		group: "Other Recipes",
		ingredients: [
			{ value: "Black Tea", slot: "Ingredient 1" },
			{ value: "Milk+", slot: "Ingredient 2" },
		],
		baseValue: { value: 1194, unit: "G" },
		effect: "Chat Friendship Boost Lv. 3",
		usedForFestival: "Hearth Day",
		whereToUnlock: "Nadine's Bistro",
	},
	{
		name: "Spring Juice",
		group: "Other Recipes",
		ingredients: [
			{ value: "Strawberry Juice", slot: "Ingredient 1" },
			{ value: "Orange Juice", slot: "Ingredient 2" },
			{ value: "Cherry Juice", slot: "Ingredient 3" },
		],
		baseValue: { value: 935, unit: "G" },
		effect: "Chat Friendship Boost Lv. 3",
		whereToUnlock: "Mini Madeleine's (Spring Only)",
	},
	{
		name: "Strawberry Jam",
		group: "Other Recipes",
		ingredients: [
			{ value: "Strawberry", slot: "Ingredient 1" },
			{ value: "Sugar", slot: "Ingredient 2" },
			{ value: "Lemon", slot: "Ingredient 3" },
		],
		baseValue: { value: 855, unit: "G" },
		effect: "Chat Friendship Boost Lv. 2",
		whereToUnlock: "Mini Madeleine's",
	},
	{
		name: "Fruit Juice",
		group: "Other Recipes",
		ingredients: [
			{ value: "Grape Juice", slot: "Ingredient 1" },
			{ value: "Apple", slot: "Ingredient 2" },
			{ value: "Orange", slot: "Ingredient 3" },
		],
		baseValue: { value: 826, unit: "G" },
		effect: "Chat Friendship Boost Lv. 2",
		whereToUnlock: "Nadine's Bistro",
	},
	{
		name: "Café au Lait",
		group: "Other Recipes",
		ingredients: [
			{ value: "Hot Coffee", slot: "Ingredient 1" },
			{ value: ["Milk", "Buffalo Milk"], slot: "Ingredient 2" },
		],
		baseValue: { value: 780, unit: "G" },
		effect: "Chat Friendship Boost Lv. 2",
		usedForFestival: "Hearth Day",
		whereToUnlock: "Bookshelves in Freya's House",
	},
	{
		name: "Cappuccino",
		group: "Other Recipes",
		ingredients: [
			{ value: "Hot Coffee", slot: "Ingredient 1" },
			{ value: ["Milk", "Buffalo Milk"], slot: "Ingredient 2" },
		],
		baseValue: { value: 780, unit: "G" },
		effect: "Chat Friendship Boost Lv. 2",
		usedForFestival: "Hearth Day",
		whereToUnlock: "Nadine's Bistro",
	},
	{
		name: "Watermelon Juice",
		group: "Other Recipes",
		ingredients: [{ value: "Watermelon", slot: "Ingredient 1" }],
		baseValue: { value: 756, unit: "G" },
		effect: "Chat Friendship Boost Lv. 2",
		whereToUnlock: "Nadine's Bistro",
	},
	{
		name: "Milk Tea",
		group: "Other Recipes",
		ingredients: [
			{ value: "Black Tea Tin", slot: "Ingredient 1" },
			{ value: ["Milk", "Buffalo Milk"], slot: "Ingredient 2" },
		],
		baseValue: { value: 674, unit: "G" },
		effect: "Chat Friendship Boost Lv. 2",
		usedForFestival: "Hearth Day",
		whereToUnlock: "Nadine's Bistro",
	},
	{
		name: "Melon Juice",
		group: "Other Recipes",
		ingredients: [{ value: "Melon", slot: "Ingredient 1" }],
		baseValue: { value: 658, unit: "G" },
		effect: "Chat Friendship Boost Lv. 2",
		whereToUnlock: "Nadine's Bistro",
	},
	{
		name: "Strawberry Tea",
		group: "Other Recipes",
		ingredients: [{ value: "Strawberry Tea Tin", slot: "Ingredient 1" }],
		baseValue: { value: 586, unit: "G" },
		effect: "Chat Friendship Boost Lv. 2",
		usedForFestival: "Hearth Day",
		whereToUnlock: "Café Madeleine",
	},
	{
		name: "Pineapple Juice",
		group: "Other Recipes",
		ingredients: [{ value: "Pineapple", slot: "Ingredient 1" }],
		baseValue: { value: 429, unit: "G" },
		effect: "Chat Friendship Boost Lv. 1",
		whereToUnlock: "Mini Madeleine's",
	},
	{
		name: "Sencha Tea",
		group: "Other Recipes",
		ingredients: [{ value: "Sencha Tea Tin", slot: "Ingredient 1" }],
		baseValue: { value: 401, unit: "G" },
		effect: "Chat Friendship Boost Lv. 1",
		usedForFestival: "Hearth Day",
		whereToUnlock: "Clara's Diner",
	},
	{
		name: "Pu'er Tea",
		group: "Other Recipes",
		ingredients: [{ value: "Pu'er Tea Tin", slot: "Ingredient 1" }],
		baseValue: { value: 401, unit: "G" },
		effect: "Chat Friendship Boost Lv. 1",
		usedForFestival: "Hearth Day",
		whereToUnlock: "Clara's Diner",
	},
	{
		name: "Oolong Tea",
		group: "Other Recipes",
		ingredients: [{ value: "Oolong Tea Tin", slot: "Ingredient 1" }],
		baseValue: { value: 401, unit: "G" },
		effect: "Chat Friendship Boost Lv. 1",
		usedForFestival: "Hearth Day",
		whereToUnlock: "Chill-Out Juice! request from Derek",
	},
	{
		name: "Chestnut Juice",
		group: "Other Recipes",
		ingredients: [{ value: "Bottled Chestnuts", slot: "Ingredient 1" }],
		baseValue: { value: 390, unit: "G" },
		effect: "Chat Friendship Boost Lv. 1",
		whereToUnlock: "Nadine's Bistro",
	},
	{
		name: "Hot Coffee",
		group: "Other Recipes",
		ingredients: [{ value: "Coffee Pack", slot: "Ingredient 1" }],
		baseValue: { value: 380, unit: "G" },
		effect: "Chat Friendship Boost Lv. 1",
		usedForFestival: "Hearth Day",
		whereToUnlock: "Café Madeleine",
	},
	{
		name: "Matcha Tea",
		group: "Other Recipes",
		ingredients: [{ value: "Matcha Tea Tin", slot: "Ingredient 1" }],
		baseValue: { value: 364, unit: "G" },
		effect: "Chat Friendship Boost Lv. 1",
		usedForFestival: "Hearth Day",
		whereToUnlock: "Clara's Diner",
	},
	{
		name: "Mint Tea",
		group: "Other Recipes",
		ingredients: [{ value: "Mint Tea Tin", slot: "Ingredient 1" }],
		baseValue: { value: 344, unit: "G" },
		effect: "Chat Friendship Boost Lv. 1",
		usedForFestival: "Hearth Day",
		whereToUnlock: "Bringing the Cafe Home request from Freya",
	},
	{
		name: "Chamomile Tea",
		group: "Other Recipes",
		ingredients: [{ value: "Chamomile Tea Tin", slot: "Ingredient 1" }],
		baseValue: { value: 344, unit: "G" },
		effect: "Chat Friendship Boost Lv. 1",
		usedForFestival: "Hearth Day",
		whereToUnlock: "Bug Chaser title, Café Madeleine",
	},
	{
		name: "Lavender Tea",
		group: "Other Recipes",
		ingredients: [{ value: "Lavender Tea Tin", slot: "Ingredient 1" }],
		baseValue: { value: 344, unit: "G" },
		effect: "Chat Friendship Boost Lv. 1",
		usedForFestival: "Hearth Day",
		whereToUnlock: "Nadine's Bistro",
	},
	{
		name: "Walnut Juice",
		group: "Other Recipes",
		ingredients: [{ value: "Bottled Walnuts", slot: "Ingredient 1" }],
		baseValue: { value: 260, unit: "G" },
		effect: "Chat Friendship Boost Lv. 1",
		whereToUnlock: "Available at the start",
	},
	{
		name: "Warm Milk",
		group: "Other Recipes",
		ingredients: [{ value: ["Milk", "Buffalo Milk"], slot: "Ingredient 1" }],
		baseValue: { value: 195, unit: "G" },
		effect: "Chat Friendship Boost Lv. 1",
		usedForFestival: "Hearth Day",
		whereToUnlock: "Available at the start, Café Madeleine",
	},
	{
		name: "Green Tea",
		group: "Other Recipes",
		ingredients: [{ value: "Green Tea Tin", slot: "Ingredient 1" }],
		baseValue: { value: 182, unit: "G" },
		effect: "Chat Friendship Boost Lv. 1",
		usedForFestival: "Hearth Day",
		whereToUnlock: "Clara's Diner",
	},
	{
		name: "Strawberry Juice",
		group: "Other Recipes",
		ingredients: [{ value: "Strawberry", slot: "Ingredient 1" }],
		baseValue: { value: 156, unit: "G" },
		effect: "Chat Friendship Boost Lv. 1",
		whereToUnlock: "Café Madeleine",
	},
	{
		name: "Tomato Juice",
		group: "Other Recipes",
		ingredients: [{ value: "Tomato", slot: "Ingredient 1" }],
		baseValue: { value: 55, unit: "G" },
		effect: "Chat Friendship Boost Lv. 1",
		whereToUnlock: "Café Madeleine",
	},
	{
		name: "Specialty Juice",
		group: "Other Recipes",
		ingredients: [
			{ value: "Spring Juice", slot: "Ingredient 1" },
			{ value: "Summer Juice", slot: "Ingredient 2" },
			{ value: "Autumn Juice", slot: "Ingredient 3" },
			{ value: "Royal Honey", slot: "Ingredient 4" },
		],
		baseValue: { value: 9511, unit: "G" },
		effect: "Pet Training Up Lv. 4",
		whereToUnlock: "Contribute (something high quality?) to the Juice Festival",
	},
	{
		name: "Autumn Blend Tea",
		group: "Other Recipes",
		ingredients: [{ value: "Autumn Blend Tea Tin", slot: "Ingredient 1" }],
		baseValue: { value: 1452, unit: "G" },
		effect: "Pet Training Up Lv. 3",
		usedForFestival: "Hearth Day",
		whereToUnlock: "Café Madeleine (Autumn Only)",
	},
	{
		name: "Autumn Juice",
		group: "Other Recipes",
		ingredients: [
			{ value: "Blueberry Juice", slot: "Ingredient 1" },
			{ value: "Grape Juice", slot: "Ingredient 2" },
			{ value: "Apple Juice", slot: "Ingredient 3" },
		],
		baseValue: { value: 1010, unit: "G" },
		effect: "Pet Training Up Lv. 3",
		whereToUnlock: "Mini Madeleine's (Autumn Only)",
	},
	{
		name: "Grape Jam",
		group: "Other Recipes",
		ingredients: [
			{ value: "Red Grapes", slot: "Ingredient 1" },
			{ value: "Sugar", slot: "Ingredient 2" },
			{ value: "Lemon", slot: "Ingredient 3" },
		],
		baseValue: { value: 1007, unit: "G" },
		effect: "Pet Training Up Lv. 3",
		whereToUnlock: "Mini Madeleine's",
	},
	{
		name: "Apple Jam",
		group: "Other Recipes",
		ingredients: [
			{ value: "Apple", slot: "Ingredient 1" },
			{ value: "Sugar", slot: "Ingredient 2" },
			{ value: "Lemon", slot: "Ingredient 3" },
		],
		baseValue: { value: 932, unit: "G" },
		effect: "Pet Training Up Lv. 2",
		whereToUnlock: "Mini Madeleine's",
	},
	{
		name: "Blueberry Jam",
		group: "Other Recipes",
		ingredients: [
			{ value: "Blueberry", slot: "Ingredient 1" },
			{ value: "Sugar", slot: "Ingredient 2" },
			{ value: "Lemon", slot: "Ingredient 3" },
		],
		baseValue: { value: 863, unit: "G" },
		effect: "Pet Training Up Lv. 2",
		whereToUnlock: "Mini Madeleine's",
	},
	{
		name: "Banana Tea",
		group: "Other Recipes",
		ingredients: [{ value: "Banana Tea Tin", slot: "Ingredient 1" }],
		baseValue: { value: 832, unit: "G" },
		effect: "Pet Training Up Lv. 2",
		usedForFestival: "Hearth Day",
		whereToUnlock: "Mini Madeleine's",
	},
	{
		name: "Mango Tea",
		group: "Other Recipes",
		ingredients: [{ value: "Mango Tea Tin", slot: "Ingredient 1" }],
		baseValue: { value: 832, unit: "G" },
		effect: "Pet Training Up Lv. 2",
		usedForFestival: "Hearth Day",
		whereToUnlock: "Nadine's Bistro",
	},
	{
		name: "Green Grape Tea",
		group: "Other Recipes",
		ingredients: [{ value: "Green Grape Tea Tin", slot: "Ingredient 1" }],
		baseValue: { value: 777, unit: "G" },
		effect: "Pet Training Up Lv. 2",
		usedForFestival: "Hearth Day",
		whereToUnlock: "Nadine's Bistro",
	},
	{
		name: "Red Grape Tea",
		group: "Other Recipes",
		ingredients: [{ value: "Red Grape Tea Tin", slot: "Ingredient 1" }],
		baseValue: { value: 755, unit: "G" },
		effect: "Pet Training Up Lv. 2",
		usedForFestival: "Hearth Day",
		whereToUnlock: "Nadine's Bistro",
	},
	{
		name: "Apple Tea",
		group: "Other Recipes",
		ingredients: [{ value: "Apple Tea Tin", slot: "Ingredient 1" }],
		baseValue: { value: 740, unit: "G" },
		effect: "Pet Training Up Lv. 2",
		usedForFestival: "Hearth Day",
		whereToUnlock: "Nadine's Bistro",
	},
	{
		name: "Cherry Tea",
		group: "Other Recipes",
		ingredients: [{ value: "Cherry Tea Tin", slot: "Ingredient 1" }],
		baseValue: { value: 647, unit: "G" },
		effect: "Pet Training Up Lv. 2",
		usedForFestival: "Hearth Day",
		whereToUnlock: "Mini Madeleine's",
	},
	{
		name: "Peach Tea",
		group: "Other Recipes",
		ingredients: [{ value: "Peach Tea Tin", slot: "Ingredient 1" }],
		baseValue: { value: 647, unit: "G" },
		effect: "Pet Training Up Lv. 2",
		usedForFestival: "Hearth Day",
		whereToUnlock: "Nadine's Bistro",
	},
	{
		name: "Orange Tea",
		group: "Other Recipes",
		ingredients: [{ value: "Orange Tea Tin", slot: "Ingredient 1" }],
		baseValue: { value: 642, unit: "G" },
		effect: "Pet Training Up Lv. 2",
		usedForFestival: "Hearth Day",
		whereToUnlock: "Mini Madeleine's",
	},
	{
		name: "Lemon Tea",
		group: "Other Recipes",
		ingredients: [{ value: "Lemon Tea Tin", slot: "Ingredient 1" }],
		baseValue: { value: 632, unit: "G" },
		effect: "Pet Training Up Lv. 2",
		usedForFestival: "Hearth Day",
		whereToUnlock: "Mini Madeleine's",
	},
	{
		name: "Blueberry Tea",
		group: "Other Recipes",
		ingredients: [{ value: "Blueberry Tea Tin", slot: "Ingredient 1" }],
		baseValue: { value: 601, unit: "G" },
		effect: "Pet Training Up Lv. 2",
		usedForFestival: "Hearth Day",
		whereToUnlock: "Mini Madeleine's",
	},
	{
		name: "Olive Tea",
		group: "Other Recipes",
		ingredients: [{ value: "Olive Tea Tin", slot: "Ingredient 1" }],
		baseValue: { value: 586, unit: "G" },
		effect: "Pet Training Up Lv. 2",
		usedForFestival: "Hearth Day",
		whereToUnlock: "Mini Madeleine's",
	},
	{
		name: "Mango Juice",
		group: "Other Recipes",
		ingredients: [{ value: "Mango", slot: "Ingredient 1" }],
		baseValue: { value: 260, unit: "G" },
		effect: "Pet Training Up Lv. 1",
		whereToUnlock: "Nadine's Bistro",
	},
	{
		name: "Banana Juice",
		group: "Other Recipes",
		ingredients: [{ value: "Banana", slot: "Ingredient 1" }],
		baseValue: { value: 260, unit: "G" },
		effect: "Pet Training Up Lv. 1",
		whereToUnlock: "Nadine's Bistro",
	},
	{
		name: "Grape Juice",
		group: "Other Recipes",
		ingredients: [{ value: "Red Grapes", slot: "Ingredient 1" }],
		baseValue: { value: 228, unit: "G" },
		effect: "Pet Training Up Lv. 1",
		whereToUnlock: "First Juice Festival, Nadine's Bistro",
	},
	{
		name: "Apple Juice",
		group: "Other Recipes",
		ingredients: [{ value: "Apple", slot: "Ingredient 1" }],
		baseValue: { value: 221, unit: "G" },
		effect: "Pet Training Up Lv. 1",
		whereToUnlock: "Mini Madeleine's",
	},
	{
		name: "Peach Juice",
		group: "Other Recipes",
		ingredients: [{ value: "Peach", slot: "Ingredient 1" }],
		baseValue: { value: 182, unit: "G" },
		effect: "Pet Training Up Lv. 1",
		whereToUnlock: "Nadine's Bistro",
	},
	{
		name: "Cherry Juice",
		group: "Other Recipes",
		ingredients: [{ value: "Cherry", slot: "Ingredient 1" }],
		baseValue: { value: 182, unit: "G" },
		effect: "Pet Training Up Lv. 1",
		whereToUnlock: "Mini Madeleine's",
	},
	{
		name: "Orange Juice",
		group: "Other Recipes",
		ingredients: [{ value: "Orange", slot: "Ingredient 1" }],
		baseValue: { value: 180, unit: "G" },
		effect: "Pet Training Up Lv. 1",
		whereToUnlock: "Mini Madeleine's",
	},
	{
		name: "Lemon Juice",
		group: "Other Recipes",
		ingredients: [{ value: "Lemon", slot: "Ingredient 1" }],
		baseValue: { value: 176, unit: "G" },
		effect: "Pet Training Up Lv. 1",
		whereToUnlock: "Nadine's Bistro",
	},
	{
		name: "Blueberry Juice",
		group: "Other Recipes",
		ingredients: [{ value: "Blueberry", slot: "Ingredient 1" }],
		baseValue: { value: 163, unit: "G" },
		effect: "Pet Training Up Lv. 1",
		whereToUnlock: "Mini Madeleine's",
	},
	{
		name: "Happy Fruit Platter",
		group: "Other Recipes",
		ingredients: [
			{ value: "Heart Watermelon", slot: "Ingredient 1" },
			{
				value: [
					"Cherry",
					"Blueberry",
					"Green Grapes",
					"Strawberry",
					"Mango",
					"Pineapple",
					"Banana",
					"Peach",
					"Orange",
					"Melon",
				],
				slot: "Ingredient 2",
			},
			{
				value: [
					"Apple",
					"Red Grapes",
					"Green Grapes",
					"Strawberry",
					"Mango",
					"Pineapple",
					"Banana",
					"Peach",
					"Orange",
					"Melon",
				],
				slot: "Ingredient 3",
			},
		],
		baseValue: { value: 3274, unit: "G" },
		effect: "Happy Energy Gain Lv. 4",
		whereToUnlock: "Sprite's Bazaar Stand",
	},
	{
		name: "Happy Chef Salad",
		group: "Other Recipes",
		ingredients: [
			{ value: ["Egg", "Silkie Egg"], slot: "Ingredient 1" },
			{ value: "Corn", slot: "Ingredient 2" },
			{ value: "Onion", slot: "Ingredient 3" },
			{
				value: [
					"Cucumber",
					"Onion",
					"Asparagus",
					"Tomato",
					"Red Bell Pepper",
					"Carrot",
					"Turnip",
					"Sweet Potato",
					"Pumpkin",
					"Eggplant",
				],
				slot: "Ingredient 4",
			},
		],
		baseValue: { value: 1233, unit: "G" },
		effect: "Happy Energy Gain Lv. 3",
		whereToUnlock: "Sprite's Bazaar Stand",
	},
	{
		name: "Happy Mushroom Fry",
		group: "Other Recipes",
		ingredients: [
			{ value: "Mushroom (any)", slot: "Ingredient 1" },
			{ value: "Salt", slot: "Ingredient 2" },
		],
		baseValue: { value: 662, unit: "G" },
		effect: "Happy Energy Gain Lv. 2",
		whereToUnlock: "Sprite's Bazaar Stand",
	},
	{
		name: "Happy Forest Mix",
		group: "Other Recipes",
		ingredients: [{ value: "Walnut", slot: "Ingredient 1" }],
		baseValue: { value: 130, unit: "G" },
		effect: "Happy Energy Gain Lv. 1",
		whereToUnlock: "Sprite's Bazaar Stand",
	},
];
export const ingredients: string[] = [
	"Amur Minnow",
	"Apple",
	"Apple Jam",
	"Apple Juice",
	"Apple Tea Tin",
	"Asparagus",
	"Autumn Blend Tea Tin",
	"Autumn Juice",
	"Avocado",
	"Baguettes",
	"Banana",
	"Banana Juice",
	"Banana Tea Tin",
	"Barbel Steed",
	"Basa",
	"Bighead Carp",
	"Bitterling",
	"Black Bass",
	"Black Tea",
	"Black Tea Tin",
	"Blueberry",
	"Blueberry Jam",
	"Blueberry Juice",
	"Blueberry Tea Tin",
	"Bluegill",
	"Bok Choy",
	"Bottled Chestnuts",
	"Bottled Walnuts",
	"Bread",
	"Breadcrumbs",
	"Broccoli",
	"Brown Trout",
	"Buckwheat Flour",
	"Buffalo Milk",
	"Buffalo Milk+",
	"Burdock",
	"Butter (any)",
	"Butter+",
	"Cabbage",
	"Carrot",
	"Castella",
	"Cauliflower",
	"Chamomile",
	"Chamomile Tea Tin",
	"Char",
	"Cheese (any)",
	"Cheese+",
	"Cherry",
	"Cherry Juice",
	"Cherry Salmon",
	"Cherry Tea Tin",
	"Chestnut",
	"Chili Pepper",
	"Chocolate",
	"Coffee Pack",
	"Common Mushroom",
	"Cooked Rice",
	"Corn",
	"Crucian Carp",
	"Cucumber",
	"Curled Chili Pepper",
	"Curry Powder",
	"Curry Rice",
	"Dace",
	"Daikon Radish",
	"Dark Chub",
	"Eel",
	"Egg",
	"Egg+",
	"Eggplant",
	"Fish Cake",
	"Focaccia Bread",
	"Fried Tofu",
	"Garlic",
	"Giant Tomato",
	"Golden Blend Tea Tin",
	"Goldfish",
	"Grape Jam",
	"Grape Juice",
	"Grape Oil",
	"Grayling",
	"Green Bell Pepper",
	"Green Grape Tea Tin",
	"Green Grapes",
	"Green Onion",
	"Green Tea Tin",
	"Heart Watermelon",
	"Herb Butter",
	"Herb Oil",
	"Honey (any)",
	"Hot Coffee",
	"Icefish",
	"Jewel Pineapple",
	"Killifish",
	"Lavender",
	"Lavender Tea Tin",
	"Lemon",
	"Lemon Juice",
	"Lemon Tea Tin",
	"Mango",
	"Mango Tea Tin",
	"Marbled Eel",
	"Masu Trout",
	"Matcha Tea Tin",
	"Matsutake Mushroom",
	"Mayonnaise (any)",
	"Mayonnaise+",
	"Melon",
	"Melon Tea Tin",
	"Milk",
	"Milk+",
	"Mint",
	"Mint Tea Tin",
	"Miso",
	"Mixed Salad",
	"Mochi",
	"Monarch Mushroom",
	"Morel Mushroom",
	"Mugitsuku",
	"Mushrom (any)",
	"Mushroom (any)",
	"Napa Cabbage",
	"Nile Perch",
	"Nut Oil",
	"Oil",
	"Olive Oil",
	"Olive Tea Tin",
	"Omelet",
	"Onigiri",
	"Onion",
	"Oolong Tea Tin",
	"Orange",
	"Orange Juice",
	"Orange Tea Tin",
	"Pale Chub",
	"Pasta",
	"Peach",
	"Peach Juice",
	"Peach Tea Tin",
	"Pepper",
	"Pineapple",
	"Pineapple Tea Tin",
	"Pond Smelt",
	"Potato",
	"Pu'er Tea Tin",
	"Pumpkin",
	"Radish",
	"Rainbow Trout",
	"Red Bell Pepper",
	"Red Grape Tea Tin",
	"Red Grapes",
	"Refined Rice Flour",
	"Rice",
	"Rice Flour",
	"Royal Honey",
	"Salmon",
	"Salt",
	"Sashimi",
	"Sculpin",
	"Seaweed",
	"Sencha Tea Tin",
	"Shiitake Mushroom",
	"Shimeji Mushroom",
	"Silkie Egg",
	"Silkie Egg+",
	"Silver Carp",
	"Snakehead",
	"Soy Milk",
	"Soy Sauce",
	"Soybean",
	"Spice",
	"Spinach",
	"Spring Blend Tea Tin",
	"Spring Juice",
	"Star Potato",
	"Stone Moroko",
	"Strawberry",
	"Strawberry Jam",
	"Strawberry Juice",
	"Strawberry Tea Tin",
	"Sugar",
	"Summer Blend Tea Tin",
	"Summer Juice",
	"Summer Tea Leaves",
	"Supreme Curry",
	"Sweet Potato",
	"Sweetfish",
	"Tamoroko",
	"Tempura",
	"Three-Forked Carrot",
	"Three-Lips Carp",
	"Tofu",
	"Tomato",
	"Turnip",
	"Urchin",
	"Vinegar",
	"Walnut",
	"Watermelon",
	"Watermelon Tea Tin",
	"Wheat Flour",
	"White Bread",
	"White Breadcrumbs",
	"Willow Shiner",
	"Yellow Perch",
	"Yogurt+",
];
